// feat-017 · i18n English source of truth (ADR-0020 后果 · memory: chinese-copy-via-m3).
//
// Only the NEW live-mode user-facing copy is externalized here (upload UI, mode banner, live
// run/empty/error states). The existing SCRIPTED story copy stays in fixtures/*.ts — it is
// story-only and already carries `⚠ 待 Danny 审字` markers there; re-homing it is out of this slice.
//
// zh.ts is AUTO-GENERATED by scripts/i18n-zh.mjs via MiniMax-M3 (I direct M3; I do NOT hand-write
// Chinese). `type Dict = typeof en` — zh.ts must satisfy this shape.
//
// ⚠ 待 Danny 审字：本文件所有英文 copy（Venus-facing）。

export const en = {
  // ── mode banner / switch ──────────────────────────────────────────────────
  mode: {
    storyLabel: 'Story',
    liveLabel: 'Live',
    storyHint: 'A scripted walkthrough — the same demo the room sees.',
    liveHint: 'Bring your own team in — upload a few files and ask.',
    switchToLive: 'Try it with your team',
    switchToStory: 'Back to the walkthrough',
  },

  // ── upload panel (live mode Onboarding) ───────────────────────────────────
  upload: {
    title: 'Bring your team in',
    caption:
      "Give it what you'd hand a new manager on day one — a few resumes, a project weekly, a roster. It reads them and your team grows below.",
    drop: 'Drop files here, or choose',
    choose: 'Choose files',
    accepted: 'PDF, Word, Excel, CSV, Markdown, or text',
    ingestingLabel: 'Reading your files…',
    readyLabel: 'Your team is ready',
    errorLabel: "Couldn't read those files",
    retry: 'Try again',
    grownFrom: 'Grown from',
    privacyNote: 'Nothing is scored about any person — only what they do and own.',
    empty: 'No files yet. Upload a few to see your team appear.',
  },

  // ── Your team, live ───────────────────────────────────────────────────────
  team: {
    liveEyebrow: 'From your uploads',
    emptyTitle: 'Your team will appear here',
    emptyBody: 'Upload a few files above and the people and projects grow from them.',
  },

  // ── Nexus, live ───────────────────────────────────────────────────────────
  nexus: {
    liveThinking: 'Working it through — live',
    liveRunning: 'Thinking…',
    liveReady: 'The read is ready',
    liveError: 'Something went wrong reaching the room.',
    askPlaceholder: 'Ask about your team…',
    ask: 'Ask',
  },
}

export type Dict = typeof en
