import type { Dict } from "./index";

// AUTO-GENERATED by scripts/i18n-zh.mjs — MiniMax-M3 (MiniMax-M3) transcreation of en.ts.
// Do NOT hand-edit; re-run the script after editing en.ts. ⚠ Draft / 待 Danny 审字.
export const zh: Dict = {
  "team": {
    "liveEyebrow": "来自你上传的内容",
    "emptyTitle": "你的团队会从这里长出来",
    "emptyBody": "在上面上传几份资料，人与项目会从里面长出来。"
  },
  "upload": {
    "title": "把团队带进来",
    "caption": "把入职第一天会递给新经理的那些东西丢给它——几份简历、一份项目周报、一份花名册。它读完，下方就长出你的团队。",
    "drop": "把文件拖进来，或点此选择",
    "choose": "选择文件",
    "accepted": "支持 PDF、Word、Excel、CSV、Markdown 或纯文本",
    "ingestingLabel": "正在读取文件…",
    "readyLabel": "团队准备好了",
    "errorLabel": "没法读取这些文件",
    "retry": "重试",
    "grownFrom": "源自",
    "privacyNote": "不给任何人打分——只看他们在做什么、归谁管。",
    "empty": "还没有文件。传几份进来，你的团队就会出现。"
  },
  "nexus": {
    "liveThinking": "实时梳理中",
    "liveRunning": "思考中…",
    "liveReady": "解读已就绪",
    "liveError": "连接分析空间失败",
    "askPlaceholder": "问问你的团队…",
    "ask": "提问"
  },
  "mode": {
    "storyLabel": "演示",
    "liveLabel": "上场",
    "storyHint": "按脚本走一遍——和现场演示完全一样。",
    "liveHint": "把你的团队带进来——上传几份文件，直接问。",
    "switchToLive": "上你的团队试试",
    "switchToStory": "回到演示"
  }
};
