// feat-017 · i18n English source of truth (ADR-0020 后果 · memory: chinese-copy-via-m3).
//
// Only the NEW live-mode user-facing copy is externalized here (upload UI, mode banner, live
// run/empty/error states). The existing SCRIPTED story copy stays in fixtures/*.ts — it is
// story-only and stays there; re-homing it is out of this slice.
//
// zh.ts is AUTO-GENERATED by scripts/i18n-zh.mjs via MiniMax-M3 (I direct M3; I do NOT hand-write
// Chinese). `type Dict = typeof en` — zh.ts must satisfy this shape.
//
// 本文件所有英文 copy（Venus-facing）。

export const en = {
  // ── mode banner / switch ──────────────────────────────────────────────────
  mode: {
    storyLabel: 'Story',
    liveLabel: 'Live',
    storyHint: 'A scripted walkthrough — the same demo the room sees.',
    liveHint: 'Bring your own team in — upload a few files and ask.',
    switchToLive: 'Try it with your team',
    switchToStory: 'Back to the walkthrough',
  },

  // ── upload panel (live mode Onboarding) ───────────────────────────────────
  upload: {
    title: 'Bring your team in',
    caption:
      "Give it what you'd hand a new manager on day one — a few resumes, a project weekly, a roster. It reads them and your team grows below.",
    drop: 'Drop files here, or choose',
    choose: 'Choose files',
    accepted: 'PDF, Word, Excel, CSV, Markdown, or text',
    ingestingLabel: 'Reading your files…',
    readyLabel: 'Your team is ready',
    errorLabel: "Couldn't read those files",
    retry: 'Try again',
    grownFrom: 'Grown from',
    privacyNote: 'Nothing is scored about any person — only what they do and own.',
    empty: 'No files yet. Upload a few to see your team appear.',
  },

  // ── Your team, live ───────────────────────────────────────────────────────
  team: {
    liveEyebrow: 'From your uploads',
    emptyTitle: 'Your team will appear here',
    emptyBody:
      'Drop a few files on the right and the people and projects grow out of them — nothing to configure.',
  },

  // ── Nexus, live ───────────────────────────────────────────────────────────
  nexus: {
    liveThinking: 'Working it through — live',
    liveRunning: 'Thinking…',
    liveReady: 'The read is ready',
    liveError: 'Something went wrong reaching the room.',
    askPlaceholder: 'Ask about your team…',
    ask: 'Ask',
  },

  // ── lite shell (feat-024: the product shell behind the story/lite wall) ───
  lite: {
    tabTeam: 'Your team',
    tabRoom: 'The room',
    tabPlaybooks: 'Playbooks',

    // ── Team grouping view (feat-025 Q2: cluster people cards by department/role) ──
    groupAllLabel: 'Grouped by team',
    groupUngrouped: 'Everyone else',
    groupCollapse: 'Collapse',
    groupExpand: 'Expand',
    groupCountOne: 'person',
    groupCountMany: 'people',

    // ── The room — thin pan/zoom canvas (feat-025 Q3) ──
    roomCanvasHint: 'Drag to move · scroll to zoom',
    roomCanvasReset: 'Reset view',

    // ── Playbooks screen (feat-025 Q1: honest empty state, anchored to future capability) ──
    playbooksEyebrow: 'Coming soon',
    playbooksTitle: 'Playbooks grow from the way your team already works',
    playbooksBody:
      'Once Avery is wired into your own SOPs, checklists, and past decisions, it distills them into reusable playbooks — so the next time a familiar situation lands, the room already knows your house rules.',
    playbooksSlotRoster: 'Your onboarding and handover SOPs become step-by-step playbooks.',
    playbooksSlotIncident: 'Recurring situations turn into a saved play the room runs the same way each time.',
    playbooksSlotPack: 'Industry packs (starting with the hospitality pack) drop in pre-built plays you can adapt.',
    playbooksSlotLabel: 'What will live here',
    playbooksComingSoon: 'Not connected yet — this is a preview of where Avery is headed.',
    playbooksEmptyTag: 'No playbooks yet',

    // Your team — briefing header (real numbers from ingestion) + weak handoffs
    briefingEyebrow: 'From your uploads',
    metricsLabel: 'Team at a glance',
    handoffsTitle: 'Worth your attention today',
    handoffsEmpty: 'Nothing needs you right now — your uploads read steady.',
    handoffOpen: 'Open the project',

    // Upload empty state (the left spine speaks for itself — no scripted placeholders)
    emptyEyebrow: 'Getting started',
    emptyHintRoster: 'A team roster or a few resumes — the people appear as cards.',
    emptyHintProject: 'A project plan or weekly update — the projects line up next to them.',
    emptyHintPrivacy: 'No one gets scored. Avery only keeps what people do and own.',

    // Lanes
    peopleLane: 'People',
    projectLane: 'Projects',

    // The room — empty state
    roomEmptyTitle: 'Bring a situation to the room',
    roomEmptyBody:
      'Describe what is on your mind about the team — it thinks it through against your uploads and comes back with a read.',

    // Composer references (live corpus only)
    refAll: 'All',
    refPeople: 'People',
    refProjects: 'Projects',
    refAdd: 'Add a reference',
    refSearch: 'Reference a person or project',
    refEmpty: 'Upload a few files first — people and projects appear here.',

    // Thin read-only detail overlay (pure live payload)
    detailAria: 'Detail',
    detailClose: 'Close',
    detailPersonEyebrow: 'Teammate',
    detailProjectEyebrow: 'Project',
    detailTenure: 'Tenure',
    detailOwns: 'Owns',
    detailCollab: 'Working with',
    detailSummary: 'Summary',
    detailProgress: 'Progress',
    detailBlockers: 'Worth a closer look',
    detailSignals: 'What the documents say',
    detailSource: 'From your uploads',
    detailGone: 'This card is no longer in your uploads.',
  },
}

export type Dict = typeof en
