import type { Dict } from "./index";

// AUTO-GENERATED by scripts/i18n-zh.mjs — MiniMax-M3 (MiniMax-M3) transcreation of en.ts.
// Do NOT hand-edit; re-run the script after editing en.ts. ⚠ Draft / 待 Danny 审字.
// (feat-025: only the NEW lite keys were re-run through M3; existing story-shared sections
//  kept byte-identical to the prior committed translation to leave story copy untouched.)
export const zh: Dict = {
  "mode": {
    "storyLabel": "演示",
    "liveLabel": "实用",
    "storyHint": "照着脚本走一遍，和现场看到的演示完全一样。",
    "liveHint": "带上你自己的团队——上传几份文件，开口问就行。",
    "switchToLive": "用你的团队试试",
    "switchToStory": "回到演示"
  },
  "upload": {
    "title": "把你的团队带进来",
    "caption": "把它当作新经理第一天拿到的那叠东西 —— 几份简历、一份项目周报、一份花名册。它读完后，你的团队就在下面长出来。",
    "drop": "把文件拖到这里，或选择",
    "choose": "选择文件",
    "accepted": "支持 PDF、Word、Excel、CSV、Markdown 或文本",
    "ingestingLabel": "正在读取文件…",
    "readyLabel": "团队已就绪",
    "errorLabel": "无法读取这些文件",
    "retry": "重试",
    "grownFrom": "取材自",
    "privacyNote": "不给任何人打分 —— 只看他们做什么、负责什么。",
    "empty": "还没有文件。上传几份，团队就会出现。"
  },
  "team": {
    "liveEyebrow": "从你上传的文件里",
    "emptyTitle": "你的团队会在这里长出来",
    "emptyBody": "把几份文件拖到右侧，人和项目就会从中长出来——无需配置。"
  },
  "nexus": {
    "liveThinking": "正在仔细梳理中 — 实时",
    "liveRunning": "正在思考…",
    "liveReady": "分析好了，可以看了",
    "liveError": "暂时连不上，再试一次？",
    "askPlaceholder": "向你的团队提问…",
    "ask": "提问"
  },
  "lite": {
    "tabTeam": "你的团队",
    "tabRoom": "议事室",
    "tabPlaybooks": "操作手册",
    "groupAllLabel": "按团队分组",
    "groupUngrouped": "其他成员",
    "groupCollapse": "收起",
    "groupExpand": "展开",
    "groupCountOne": "人",
    "groupCountMany": "人",
    "roomCanvasHint": "拖动平移 · 滚动缩放",
    "roomCanvasReset": "重置视图",
    "playbooksEyebrow": "即将推出",
    "playbooksTitle": "操作手册从团队已有的工作方式中生长出来",
    "playbooksBody": "当 Avery 接入了你自己的 SOP、检查清单和过往决策后，会把它们提炼成可复用的操作手册——下次遇到类似情况，会议室已经知道你的行事规则。",
    "playbooksSlotRoster": "入职与交接的 SOP 自动转成一步步可执行的操作手册。",
    "playbooksSlotIncident": "反复出现的情况沉淀为固定打法，会议室每次都按同一套路走。",
    "playbooksSlotPack": "行业包（先从酒店业开始）会预置可直接套用的打法，你可以按需调整。",
    "playbooksSlotLabel": "这里会有什么",
    "playbooksComingSoon": "暂未接入——这里是 Avery 接下来会落地的方向预览。",
    "playbooksEmptyTag": "暂无操作手册",
    "briefingEyebrow": "来自你上传的文件",
    "metricsLabel": "团队一览",
    "handoffsTitle": "今天值得你留意",
    "handoffsEmpty": "暂时没有需要你出面的事——文件读起来一切平稳。",
    "handoffOpen": "打开项目",
    "emptyEyebrow": "开始上手",
    "emptyHintRoster": "团队花名册或几份简历都可以——成员会以卡片形式出现。",
    "emptyHintProject": "项目计划或周报都可以——项目会排在他们旁边。",
    "emptyHintPrivacy": "不给任何人打分。Avery 只记下每个人负责和承担的内容。",
    "peopleLane": "人员",
    "projectLane": "项目",
    "roomEmptyTitle": "把眼前的事带进议事室",
    "roomEmptyBody": "把团队里让你放心不下的事写下来——它会对照你上传的文件想清楚，再给你一份判断。",
    "refAll": "全部",
    "refPeople": "人员",
    "refProjects": "项目",
    "refAdd": "添加参考",
    "refSearch": "引用一位成员或一个项目",
    "refEmpty": "先上传几份文件——成员和项目会出现在这里。",
    "detailAria": "详情",
    "detailClose": "关闭",
    "detailPersonEyebrow": "团队成员",
    "detailProjectEyebrow": "项目",
    "detailTenure": "在职时长",
    "detailOwns": "手上的事",
    "detailCollab": "协作中的伙伴",
    "detailSummary": "概览",
    "detailProgress": "进展",
    "detailBlockers": "值得再看一眼",
    "detailSignals": "文件里提到的",
    "detailSource": "出处：你上传的文件",
    "detailGone": "这张卡片已不在你上传的文件里。"
  }
};
