import type { Dict } from "./index";








// AUTO-GENERATED by scripts/i18n-zh.mjs (+ scripts/i18n-zh-lite2-delta.mjs for the lite2 section)
// — MiniMax-M3 (MiniMax-M3) transcreation of en.ts. Do NOT hand-edit; re-run after editing en.ts.
// ⚠ Draft / 待 Danny 审字.
// (feat-025: only the NEW lite keys were re-run through M3; existing story-shared sections
//  kept byte-identical to the prior committed translation to leave story copy untouched.)
// ⚠ HAND-WRITTEN, NOT YET M3 (feat-032): upload.filesTitle ("你的文件") and upload.filesChunks
//  ("处引用") were typed in by hand — at the time the generator was FULL-REGEN only, and a
//  full re-run re-translates every story-shared section (drift + token risk the kickoff warns
//  against). Source keys live in en.ts. Fold these into M3 on the next DIRECTED zh pass so they
//  stop masquerading as generated output.
// ⚠ HAND-WRITTEN, NOT YET M3 (feat-033): the whole lite."notes*" block + lite.tabNotes were typed
//  in by hand for the same reason. Source keys live in en.ts. Danny 审字 pending.
// NOTE (feat-034 merge): scripts/i18n-zh.mjs now HAS a directed-section mode
//  (`node scripts/i18n-zh.mjs ask`) — the ask.* section below was generated through it.
//  The feat-032/033 hand-written keys above can be folded the same way (e.g. `… upload lite`).
// NOTE (feat-034 stage C): the 9 NEW ask.* keys (offlinePreview / expiryHint / revoke /
//  revoked* / expired*) came out of a directed `i18n-zh.mjs ask` M3 run; the run's churn on the
//  ALREADY-FINAL ask keys was reverted (locked copy stays byte-identical), only the new keys were
//  folded in. Danny 审字 pending on the new keys.
// NOTE (lite-live-v02 sync, integrate/v02-main-sync): the lite2.* section below was generated via
//  scripts/i18n-zh-lite2-delta.mjs (v02's own generator) and is independent of the notes above,
//  which describe the shared lite.*/ask.* sections only.
// ⚠ HAND-WRITTEN, NOT YET M3 (rich-align-0722/01-02): lite2.projectsRisk{Label,High,Medium,Low}
//  (风险/高风险/中风险/低风险) + lite2.projectsMilestone{sLabel,Done,Active,Blocked,Upcoming,Other}
//  (里程碑/已完成/进行中/受阻/未开始/其他) were typed in by hand — an AFK offline campaign pass,
//  trivial fixed copy, no directed M3 run made. Source keys live in en.ts. Fold into the next
//  DIRECTED zh pass; Danny 审字 pending.
// ⚠ HAND-WRITTEN, NOT YET M3 (rich-align-0722/03): lite2.selfReport{LoadLabel,MoodLabel,Mood*,
//  Provenance} (自述负载/自述情绪/如常/偏紧/吃紧/其他 + 《{source}》记录的本人自述). The mood words
//  are DELIBERATELY the four-token vocabulary the AFK gate scans (如常/偏紧/吃紧) — keep them verbatim.
//  AFK offline pass, no directed M3; Danny 审字 pending (verified as 复核项 in 03 acceptance).
// ⚠ HAND-WRITTEN, NOT YET M3 (rich-align-0722/04): lite2.directory* (11 keys — team 目录形态的组别/
//  情绪筛选 chip 文案 + 口径角标「按本人自述筛选」+ 空筛选态). Draft; Danny 审字 pending.
// ⚠ HAND-WRITTEN, NOT YET M3 (rich-align-0722/08): lite2.playbooksLibrary* + playbooksCardTagsAria
//  (5 keys — 满态方法库网格屏头). Draft; Danny 审字 pending.
// ⚠ HAND-WRITTEN, NOT YET M3 (rich-align-0722/09): lite2.restart{Action,Confirm,Aria}
//  (3 keys — 设置菜单第三行「重新开始」). Draft; Danny 审字 pending.
// NOTE (feat-047): lite2.tabNotes + the 14-key lite2.notes* block are NEW in this run — 0 fresh
//  M3 calls (script reused zh.lite's already-approved translation verbatim since the key names
//  match byte-for-byte; see scripts/i18n-zh-lite2-delta.mjs's sharedKeys logic). Danny 审字
//  inherits from the original feat-033 hand-written note above (same source strings).
// ✅ M3-PASSED 2026-07-18 (feat-068): upload.ingestingHint / upload.ingestingElapsed /
//  lite2.onboardUploadHint / lite2.onboardUploadElapsed —— ingest 真等待态（100–120s）的等待预期
//  文案。草稿经 MiniMax 过了一轮，采纳它的精简、但保留「逐页通读」——那半句是让「等两分钟」
//  变得可接受的唯一理由（用户默认以为在上传，上传不该要两分钟；读完每一页才该要）。
//  后续若要再动这几条，走定向模式 `node scripts/i18n-zh.mjs upload lite2`，别全量重跑——
//  会重译已锁定的 story 共享段，正是 kickoff 警告的 drift + token 风险。源 key 在 en.ts。
// ⚠ ZH DRAFT, PENDING M3 (feat-068 · ZH-03): the whole NEW `transport.*` section (9 keys) was
//  hand-drafted. Background: feat-068 introduced httpErrorMessage() **in English only**, in the
//  same wave that made ZH the production default — so a 三亚 manager who tripped the rate limit
//  read 「无法读取这些文件」 stacked on `ingest: too many requests — wait 34s and try again.`,
//  where the English line was the one carrying the actual information. These 9 keys are the fix.
//  Run them through the directed generator (`node scripts/i18n-zh.mjs transport`) before 07-25 —
//  source keys live in en.ts. Do NOT full-regen: that re-translates the locked story-shared
//  sections (drift + token risk the kickoff warns against).
// ⚠ HAND-WRITTEN, act-first (棒D · 布局与真部件战役 2026-07-22): lite2.homeGapFilterActive「活跃」
//  + lite2.homeGapsFilterEmpty「这个状态下暂时没有。」——差距面板三态筛选 chip 的两个新词。
//  故意没跑 i18n-zh-delta.mjs：本文件对象体里有 8 行 feat-057 红线注释（homeDecisions 段），
//  delta 的 JSON.stringify 写法会连它们一起抹掉，只能靠 --allow-comment-loss 再手工贴回——
//  为两个短标签冒抹掉红线注释的风险不划算。源键在 en.ts（唯一源）。其余复用既有键：Settled /
//  Set aside chip = gapResolvedBadge/gapDismissedBadge（与「多看一眼」历史徽章一字不差），
//  证据来源签 = handoffEvidenceTag。Danny 审字 pending（与 feat-057 同批人话口径）。
// ⚠ HAND-WRITTEN, act-first (棒E · 布局与真部件战役 2026-07-22): lite2.searchPlaceholder「搜索成员、
//  项目…」+ lite2.searchAria「搜索成员与项目」+ lite2.searchEmpty「没有匹配的成员或项目。」——
//  顶栏真搜索的三个新词。同 棒D 之由：对象体里的 8 行 feat-057 红线注释挡着 delta，为三个极短
//  无歧义的词不冒抹掉红线注释的风险。结果分组标签复用既有 refPeople/refProjects（人员/项目）。
//  🔴 searchEmpty=零匹配，与 refEmpty=零数据 是两回事，措辞刻意分开。源键在 en.ts。Danny 审字 pending。
// ⚠ HAND-WRITTEN, act-first (棒F · 布局与真部件战役 2026-07-22): lite2.askAveryLabel「问 Avery」
//  + lite2.askAveryAria「向 Avery 提问」+ lite2.askAveryPlaceholder「向 Avery 问一句关于团队的事…」——
//  悬浮「问 Avery」入口的三个新词。同 棒D/棒E 之由：对象体里的 8 行 feat-057 红线注释挡着 delta，
//  为三个极短词不冒抹掉红线注释的风险。🔴 品牌 Avery 不译，label 正好是「问 Avery」（Danny 拍板）——
//  与 feat-034 Ask 的「快问」两名不撞、绝不叫 Nexus。源键在 en.ts。Danny 审字 pending。
// ⚠ ZH DRAFT, PENDING M3 (feat-068 · ZH-02): the 11 NEW triage keys duplicated into BOTH lite.*
//  and lite2.* (handoffToneLabel / handoffAction / handoffEvidenceFallback / handoffEvidenceTag /
//  handoffStatus{AtRisk,Blocked} / personRead{Owns,ListSeparator,None} / personCardOpenAria /
//  groupOwns) were hand-drafted. Background: 「今天值得你留意」——首页最重要的那块面板——的标签
//  全是英文，因为 teamData.ts 的 liveHandoffs()/liveRead() 把英文句子直接拼进了派生数据
//  （线上实测：`WORTH A CLOSER LOOK` / `Take a look at 客房系统改造` / `Owns 客房系统改造负责人,
//  后端接口交付`）。这些串是**前端派生**的，后端改不动，只能在前端修。
//  拟稿时刻意避开逐字直译：`Take a look at {project}` 没有译成「看一下 {project}」（英文动词在
//  前的语序，中文读起来就是机翻），而是把项目名摆到句首再说要你做什么；眉签复用了字典里已锁的
//  「多看一眼」，没有另造同义词。
//  ⚠ 已知瑕疵留给 M3 判断：personReadOwns「负责：{items}」在 owns 条目本身就以「负责人」结尾时
//  会读成「负责：客房系统改造负责人」（语义重复）。这是上游抽取的语料质量问题，EN 侧同样存在
//  （`Owns 客房系统改造负责人`），不是本次引入的回归——若要在文案层规避，需要换一个不含「负责」
//  的框架词，但「负责」是 lite.emptyHintPrivacy 已锁的用词。
//  Run them through the directed generator (`node scripts/i18n-zh.mjs lite lite2`) before 07-25 —
//  source keys live in en.ts. Do NOT full-regen.
// ✍ HAND-WRITTEN, NOT M3 (feat-058): lite2.draft* 那 20 条（应用内草稿框）由本棒直接定稿——
//  AGENTS.md 已授权中文文案 act-first，不标"待审"。源 key 在 en.ts；后续若要重译走定向模式
//  `node scripts/i18n-zh.mjs lite2`，别全量重跑（会重译已锁定的 story 共享段）。
// NOTE (feat-069, via scripts/i18n-zh-delta.mjs): only the keys listed below were NEW in this
//  run; every other key in these sections was carried over byte-identical from the previous zh.ts.
//  lite — M3: streamNudgeRedline, streamNudgeChain, streamAskDrafted, streamAdviceReady, streamAdviceDone, streamFailed, streamErrorUnknown
//  ⚠ Draft / 待 Danny 审字.
// NOTE (feat-069, via scripts/i18n-zh-delta.mjs): only the keys listed below were NEW in this
//  run; every other key in these sections was carried over byte-identical from the previous zh.ts.
//  lite2 — reused verbatim from zh.lite: streamNudgeRedline, streamNudgeChain, streamAskDrafted, streamAdviceReady, streamAdviceDone, streamFailed, streamErrorUnknown
//  ⚠ Draft / 待 Danny 审字.
// NOTE (open-loop-0720, 语言+观感开关): lite2.langSwitch*/lookSwitch* 6 个键是本批新增（顶栏
//  两个新开关的按钮文案 + aria-label）。本该走 `node scripts/i18n-zh-delta.mjs lite2`，但这个
//  worktree 没有 eval-harness/.env（MINIMAX_API_KEY 未拷进来，主检出才有、且本棒禁止碰主检出）
//  ——改用同一套 director 口径（同一份系统提示词）手动过 `mmx text chat`（mmx-cli，全局
//  ~/.mmx 凭据，与 eval-harness/.env 无关）得到译文，再按脚本会产出的同一种合并方式手工落盘。
//  中文纯度门（verify-zh-purity.mjs）已过：6 个值全是纯中文，零拉丁字符。其余键一个字未动。
//  ⚠ Draft / 待 Danny 审字。
// NOTE (avery-sync zh-purity, 2026-07-20): lite.advice*/lite2.advice* 两组 29 键是本批新增
//  （Room advice 结构化卡：LiteAdviceCard.tsx 之前渲染的 ~20 个结构标签 + confidence/escalation
//  两处后端枚举徽章词，全部零 i18n 硬编码——ZH 是生产默认，中文客户每次真跑一次问答都会在
//  判读卡上看见英文标签）。这个 worktree 同样没有 eval-harness/.env（MINIMAX_API_KEY 未拷进
//  来，主检出才有、且本棒禁止碰主检出）——沿用 open-loop-0720 那条注记同一套办法：同一份
//  director 系统提示词（scripts/i18n-zh.mjs 的 SYS），手动过 `mmx text chat` 拿到译文，
//  再按脚本会产出的同一种合并方式手工落盘。唯一手动调整：escalation 徽章词 HRBP 那一档，
//  M3 给的是「人力业务伙伴」，为了和其余徽章词（低/中/高、法务、薪酬、高管层）保持同等长度
//  的贴角短词，裁成「人力伙伴」——其余 28 个键逐字采纳 M3 输出，未手改一字。
//  ⚠ Draft / 待 Danny 审字。
// NOTE (avery-sync aria-zh, 2026-07-20): mode.switchAria + lite.*/lite2.* 两组共 33 个新键是
//  本批新增 —— ZH 生产构建里 ~88 处硬编码英文 aria-label/title（顶栏、composer、议事室终端、
//  空态区块等结构性无障碍属性）的修法，见 en.ts 同批键上的注释。中文纯度门
//  （verify-zh-purity.mjs）扫的是 innerText，结构上看不见这些属性，这批缺陷是靠
//  `grep -rn aria-label src/` 人工枚举揪出来的，不是任何现成门抓到的 —— 新增的
//  verify-aria-zh.mjs 补上这个结构性盲区。这个 worktree 同样没有 eval-harness/.env
//  （MINIMAX_API_KEY 未拷进来，主检出才有、且本棒禁止碰主检出）——沿用 open-loop-0720/
//  avery-sync zh-purity 那两条注记同一套办法：同一份 director 系统提示词（改写自
//  scripts/i18n-zh.mjs 的 SYS，补了一段"这批是 aria-label，屏幕阅读器会整句念出来，必须是
//  通顺人话"的专项说明 + 术语表锁定），手动过 `mmx text chat` 拿到译文，再按脚本会产出的
//  同一种合并方式手工落盘。projectsOpenAria 的译文与 lite2 里已经 Danny 审过的同名键
//  （"打开 {title}"）逐字重合——M3 独立译出同一个结果，未手工对齐，视为交叉验证。
// NOTE (Blockers 5a, 2026-07-20): lite2.auth* 22 个键**不是新译文**，是**搬家**——它们此前
//  就地写死在 src/lite2/auth/AuthPanel.tsx 的私有 `COPY` 字典里，且已经在生产上跑了两天。
//  这里逐字照搬那份中文，**刻意不过 M3**：重译等于让客户已经看过的词无缘无故变一遍
//  （线上词漂），而这批词本身没有任何质量问题。搬家的动机是两件事：① 私有字典不订阅
//  localeStore，语言开关点了它不变；② 它对所有扫 en.ts/zh.ts 的门（中文纯度门 / aria 门）
//  是隐形的——一份没人扫得到的文案等于没有质量信号。搬进来后两件事一起解决。
//  故本批**零 M3 调用**，也不标"待审"（AGENTS.md 已授权中文文案 act-first，且这批早已上线）。
//  33 个键逐字采纳 M3 输出，未手改一字。
//  ⚠ Draft / 待 Danny 审字。
// NOTE (open-loop-0720, zh-purity 收尾, 2026-07-20): 两类改动都是本批新增。
//  ① lite2.visionMockSkillsTitle/Body（Skills/tools/onboarding/review/skill → 技能/工具/入职/
//  复盘/技能）：Danny 原话「行业通用黑话留着（更自然）、有现成自然中文说法的翻掉」——demo/agent/
//  prompt 判定为前者，保留原文，未过 M3（这几处是嵌进已锁定长句里的局部替换，整句重跑 M3 会
//  连累前后已审文字漂移，属于本文件开头反复警告的那类风险，改用人工按词替换）。
//  ② lite.terminalTitle / lite2.roomToolLabel / lite2.roomManifestLabel 3 个全新键（终端标题
//  + 两个说话人前缀徽标，此前是硬编码英文字面量）：过了一遍同一份 director 系统提示词的
//  `mmx text chat`（本 worktree 同样没有 eval-harness/.env，办法同 open-loop-0720/avery-sync
//  两条老注记）。roomToolLabel/roomManifestLabel 两个 M3 独立译出的结果与人工拟稿逐字重合
//  （工具/结果），未手改。terminalTitle 人工拟稿是「它是怎么想明白的」——刻意复用 v02 双生键
//  roomFlowTitle 已经 Danny 审过的原句（同一个终端标题，两壳只是外壳不同），M3 给的替代句
//  「它是怎么推出来的」语气也通，但为了 v01/v02 措辞一致性没有采纳。
//  ⚠ Draft / 待 Danny 审字（除 terminalTitle 外两键与 M3 独立交叉验证一致）。
// NOTE (open-loop-0720, 重看上手引导入口, 2026-07-20): lite2.playbooksReopenOnboarding 1 个
//  全新键——Playbooks 屏新增的"重新打开上手向导"链接文案。同一份 director 系统提示词过了
//  `mmx text chat`，M3 独立译出的结果与人工拟稿（任务原话建议的措辞）逐字重合（重看上手引导），
//  未手改一字。
//  ⚠ Draft / 待 Danny 审字（与 M3 独立交叉验证一致）。
// NOTE (对抗复审 fixA2, 2026-07-20): lite.briefingHeadlineFilesPartial / lite2.同名键 2 个全新
//  键——文件没有全部读进去时的 headline 变体（此前中文 headline 完全不提文件数，见
//  shared/briefing.ts::localizeBriefing 头部注释）。人工拟稿（沿用已锁定的 briefingHeadline
//  句式「你的团队：{people} 位成员，{projects} 个进行中的项目」，只在前面加「读取了 N/M
//  份文件：」这一句实指，不新造措辞风格），未过 M3——这个 worktree 同样没有
//  eval-harness/.env（MINIMAX_API_KEY 未拷进来，主检出才有、且本棒禁止碰主检出）。
//  ⚠ Draft / 待 Danny 审字。
// NOTE (0729 大白话命名 pass · ADR-0031 · 导演手改，未过 M3——词表 Danny 2026-07-29 逐条审字
//  通过，属「审定词替换」而非新译)：仅动 lite2 段。5 个 tab 主名（今天/团队/问 Avery/值得注意/
//  完整版预告）+ 屏内词族（观察记录/今日提醒/资料对不上的地方/Avery 的分析/分析过程/判断依据/
//  资料概览）+ 待办动作词统一「加到待办」+ 3 处「会议室」误译随 tab 新名归一为 Avery。
//  v01 lite 段一字未动（冻结壳保留旧词）。生成器锁定词族已同步（i18n-zh-lite2-delta.mjs 铁律 4）。
// NOTE (UIUX 棒 2026-07-20 晚, via scripts/i18n-zh-delta.mjs ×2 趟): 本次新增仅
//  lite.handoffsEmptyButLook 与 lite2.handoffsEmptyButLook（F4 · handoffs 空态不许在有风险
//  信号时说「一切平稳」），其余键逐字节保留。M3 初译用了「再看一眼」，经导演修正统一为产品
//  既定词汇「多看一眼」（简报 subhead、handoffToneLabel、tabCloserLook 全用后者；lite2 那条
//  的去处指名必须与 tab 实名「多看一眼」一致，指错名字是 bug 不是措辞偏好）。
//  按 AGENTS.md act-first：直接定稿上线，Danny 可回头调词。
// NOTE (feat-069, via scripts/i18n-zh-delta.mjs): only the keys listed below were NEW in this
//  run; every other key in these sections was carried over byte-identical from the previous zh.ts.
//  upload — M3: caption, privacyNote
//  team — M3: emptyBody
//  lite — M3: visionProofRedline, visionMockGateTitle, visionMockGateBody, notesRedlineNote, emptyHintPrivacy, adviceSignalsLabel, adviceHypothesesLabel, adviceEvidenceLabel, adviceConfidenceLabel, adviceActionsLabel
//  ask — M3: redlineNote, redlineNoteOffline
//  ⚠ Draft / 待 Danny 审字.
// NOTE (feat-069, via scripts/i18n-zh-delta.mjs): only the keys listed below were NEW in this
//  run; every other key in these sections was carried over byte-identical from the previous zh.ts.
//  lite2 — M3: settingsAria, followupsSourceDecision, gapRealtimeTitle, gapRealtimeBody, visionSummaryLabel, visionSummary1, visionSummary2, visionSummary3, roomNoMaterialTitle, roomNoMaterialBody, roomNoMaterialCta, onboardUploadBody, homeSkeletonTitle, homeSkeletonLede, homeSkeletonDecisions, homeSkeletonGaps, homeSkeletonAttention, homeSkeletonOverview, homeGuestNote, homeTodayTitle, homeTodayEmpty, homeTodayDoneAria, homeTodayMore, homeDecisionAddFollowup, homeDecisionFollowupTitle | reused verbatim from zh.lite: notesRedlineNote, visionProofRedline, visionMockGateTitle, visionMockGateBody, emptyHintPrivacy, adviceSignalsLabel, adviceHypothesesLabel, adviceEvidenceLabel, adviceConfidenceLabel, adviceActionsLabel
//  ⚠ Draft / 待 Danny 审字.
// NOTE (feat-069, via scripts/i18n-zh-delta.mjs): only the keys listed below were NEW in this
//  run; every other key in these sections was carried over byte-identical from the previous zh.ts.
//  lite2 — M3: onboardStepOf, onboardBrowse, onboardDoorsTitle, onboardDoorsBody, onboardDoorDemoTitle, onboardDoorDemoBody, onboardDoorDemoBusy, onboardDoorDemoErrorLead, onboardDoorUploadTitle, onboardDoorUploadBody, onboardTeamCountLabel, onboardTeamCountPlaceholder, onboardRoleLabel, onboardRolePlaceholder, onboardCompanyNoteLabel, onboardCompanyNotePlaceholder, onboardCompanyNoteHint, onboardCompanyNoteHintLater, onboardNoteText, onboardNoteSource, homeDemoNote
//  ⚠ Draft / 待 Danny 审字.
export const zh: Dict = {
  "mode": {
    "storyLabel": "演示",
    "liveLabel": "实用",
    "storyHint": "照着脚本走一遍，和现场看到的演示完全一样。",
    "liveHint": "带上你自己的团队——上传几份文件，开口问就行。",
    "switchAria": "数据模式"
  },
  "upload": {
    "title": "把你的团队带进来",
    // #91 · 多选引导（⚠ HAND-WRITTEN）：一起读不只是快——几份文件互相印证，抽出来的人和
    // 项目更准（粒度闸吃的就是跨文档证据）。所以要说清"为什么"，不只是"可以"。
    "caption": "第一天交给新经理的那些——一份花名册、一份项目周报、几份简历——都丢进来。可以一次全选：几份文件一起读，比一份一份传更快，读出来的结果也更准。Avery 读完之后，会回给你能落地的判断：谁在扛什么事、项目推进到哪一步、今天最值得你看的是什么。",
    "drop": "把文件拖到这里，或选择",
    "choose": "选择文件",
    "accepted": "支持 PDF、Word、Excel、CSV、Markdown 或文本",
    "ingestingLabel": "正在读取文件…",
    // #91 ·「请保持页面打开」退役：#90 之后文件在这行字出现的那一刻就已经收好了，读取在
    // 服务器上自己跑，页面关不关都不影响。传完就走是新能力，要正面说出来，不能只把旧警告
    // 悄悄删掉（删掉一句话教不会任何人「现在可以走了」）。⚠ HAND-WRITTEN。
    "ingestingHint": "文件已经收好了。正在逐页通读，通常需要两三分钟——这期间关掉页面、去忙别的都没关系，回来在资料库里就能看到结果。",
    "ingestingElapsed": "已用时 {seconds} 秒",
    "readyLabel": "团队已就绪",
    "errorLabel": "无法读取这些文件",
    "retry": "重试",
    "grownFrom": "取材自",
    "privacyNote": "默认不给人打分——除非你们公司主动开启。Avery 只看每个人做了什么、在负责什么。",
    "empty": "还没有文件。上传几份，团队就会出现。",
    "filesTitle": "你的文件",
    "filesChunks": "处可引用片段",
    "acceptedExts": ".pdf · .docx · .xlsx · .csv · .tsv · .md · .txt",
    "acceptedLegacyNote": "旧版 .doc 和 .xls 需要先另存为新格式再上传。",
    "fileStatusIngested": "已读取",
    "fileStatusEmpty": "没读到内容",
    "fileStatusFailed": "没能读取",
    "fileStatusUnknown": "状态未知",
    // #91 · #90 的 'reading' 中间态：字节已收下、还在逐页读。任务落定后翻成上面三个终态之一。
    "fileStatusReading": "正在读取…",
    "fileStatusEmptyHint": "这份文件能打开，但里面没取出文字——扫描件或纯图片导出通常是这样。它没有任何内容进入你的团队。",
    "fileStatusFailedHint": "这份文件完全没能打开，常见原因是字符编码不匹配（另存为 UTF-8 后重新上传）。它没有任何内容进入你的团队。",
    // ── #89 · 抽取降级横幅（2026-08-11 合伙人真实翻车的正面修复）─────────────────────
    // 那天后端每次抽取都撞供应商 429、降级到正则、13 人花名册抽出 0 人；她看到的是
    // 200 +「已读取」+「今天没有要你定夺的事」——每一句都在说一切正常。后端从 feat-039
    // 起就一直诚实地发着 `extraction_mode: "degraded"`，前端一次都没读过。
    // 🔴 措辞的三条纪律（都是那天踩出来的）：
    //   ① 先摘掉用户的责任。她当时的第一反应是「我是不是传错格式了」。
    //   ② 不许说「全都没读到」——degraded 的判据是「**至少一份**掉回了正则」，其余文档
    //      可能好好抽出来了。说满就是另一个方向的假话。
    //   ③ 重试指引必须说「先删再传」：补传走 `_unique_parse_names(taken=…)`，同名文件会
    //      被改名成 `xxx(1)`，直接重传是**多一份**不是覆盖。不说这句，用户重试三次就是
    //      资料库里三份同样的文件、片段数翻三倍。
    "extractionDegradedTitle": "有文件没能读懂",
    "extractionDegradedBody": "文件都好好存在下面的资料库里——是我们这边负责读文件的服务当时没接上。所以这几份里的人和项目可能没建起来，或者建得不全。不是你传错了。",
    "extractionDegradedRetry": "想再试一次：先把那几份删掉，再重新传。直接重传不会覆盖，会变成两份。",
    // ── #91 · 异步 deposit 的两个新话面（⚠ HAND-WRITTEN）────────────────────────────────
    // jobFailedLead：deposit 秒回之后整批在服务端读挂了（红线拒收 / 全部解析失败 / 服务重启）
    // ——#90 里旧同步 422 的对应物。「没进资料库」是诚实的边界：一个字都没存、一张卡都没动。
    // 开发者英文的具体原因跟在后面当诊断（同表单保存失败的先例）。
    "jobFailedLead": "这批文件没进资料库",
    // skippedIdenticalLead：sha256 认出库里已有一模一样的字节（#90）——「超时后重传」这个
    // 最常见场景的正面答复。这是**成功**的话（东西早就在了），绝不能写成像被拒绝了。
    "skippedIdenticalLead": "这几份资料库里已经有了，没有重复保存",
    // ── #88 · 「新建一家公司」这个概念整条撤除 ───────────────────────────────────────
    // 这里原来是 againTitle / againBody（「从这里上传会新建一家公司」）+ 底下十条 switch*
    // （「这台电脑上传过的公司」那份名册）。Danny 2026-08-10 拍板：一个人从头到尾就一份
    // 档案，传文件永远是补进这一份，真要从头来是**清空**它（下面 filesEmpty* 那一族 + 硬确认）。
    // 🔴 againTitle 不能留着改用途：它的原文就是「从这里上传会新建一家公司」，而 Avery
    //    已经不做这件事了——留着就是一句假话。
    // ⚠ HAND-WRITTEN, NOT YET M3（T10 · 补资料口）——#88 之后这就是唯一的上传语义。
    "appendTitle": "给这家公司补资料",
    "appendCaption": "新文件会并进你现在看的这家公司。有好几份就一次全选——一起读更快，结果也更准。读到的新情况直接更新到卡片上；和旧资料对不上的地方，会出现在今天页等你确认。",
    "appendReadyLabel": "新资料已经并进来了",
    "appendAddedLead": "这次新增的",
    "appendConflicts": "有 {count} 处和旧资料对不上，去「今天」页看两边分别怎么写的。",
    // partner-docs-0728 · 上传口旁边的两条链接（→ /paperwork）。M3 生成，2026-07-28。
    "paperworkFormsLink": "不知道该发什么？拿一份标准表单",
    "paperworkPrivacyLink": "你上传的内容，我们怎么处理",
    // ⚠ HAND-WRITTEN, NOT YET M3（files-hub-0729/01）：下载三键。按 PRD「en 源 → zh 导演手改，
    // 短键先例」办（同 feat-032 的 filesTitle/filesChunks 那条先例）。
    // 🔴 downloadError 刻意**不说「文件没了」**：这个端点把「没有这份」和「你证明不了这是你的」
    // 编码成同一个 404（feat-038 租户隔离），前端一种都分不出来——同 fileDeleteError 的纪律。
    "download": "下载",
    "downloading": "下载中…",
    "downloadError": "这份文件刚才没能下下来，再试一次。",
    // ── #84 · 表格形态下这三颗钮只剩 icon，标题得靠 aria-label 说 ───────────────────
    // 🔴 带上文件名：一屏九行、九枚一模一样的下载 icon，读屏用户听到九次「下载」分不出
    // 自己焦点在哪一行。verify-aria-zh 扫的就是这一族（innerText 里从来没有它们）。
    // ⚠ 记一笔账：文件名是**用户数据**，可能整串是拉丁字母。verify-aria-zh 的尺子是
    //   「两个及以上连续拉丁词，或单个长度 ≥4 的拉丁词」——今天它的语料是 `w31.md`
    //   （最长片段 2–3 字符，够不着门槛）所以不红。哪天语料换成 `weekly-report.md`，
    //   这道门会对着一个**文件名**报「英文残留」。那时的正解与表单链接 URL 那条碑一样：
    //   给扫描面加一条"用户数据"豁免，**不是**放宽 ALLOW 词表，更不是把文件名从
    //   aria-label 里拿掉（拿掉就回到九个一模一样的「下载」）。
    "downloadAria": "下载「{name}」",
    "downloadingAria": "正在下载「{name}」",
    "deleteAria": "删除「{name}」",
    "rowActionsAria": "「{name}」的更多操作",
    // ── #76 · 清单长出形状：列、排序、手动刷新、诚实的加载态 ──────────────────────
    // uploaded_at / doc_kind 从 feat-032 起就在 payload 里，一直没渲染——传过三批之后
    // 分不出哪份是上周的。
    "filesRefresh": "刷新",
    "filesRefreshing": "正在刷新…",
    "filesLoading": "正在读取清单…",
    // 🔴 刻意不说「你的文件没了」：拉不到只说明我们这次没读到，与服务端有没有是两件事
    //（同 downloadError / filesCurrentEmptyRead 的纪律）。清单停在上一次的好结果上。
    "filesLoadError": "刚才没连上服务器，下面这份清单可能不是最新的。",
    "filesRetry": "再拉一次",
    // 记账（#76）：**不设** fileTime / fileKind 表头键。时间挂在 `.upload-file-meta` 那一行里
    // （逐行一句，不做表头）；「类型」单开一列是噪音——扩展名本来就在文件名里，而 doc_kind
    // 是机器词（'company'），对经理没有意义。为「以后可能要用」先建键 = 制造孤儿。
    "filesSortLabel": "排序",
    "filesSortDefault": "上传顺序",
    "filesSortTime": "最近传的在前",
    "filesSortName": "按文件名",
    "filesSortSize": "大的在前",
    // ── #84 · 真列表格的列头 ──────────────────────────────────────────────────────
    // 上面 #76 那条「不设 fileTime / fileKind 表头键」的记账在本票被推翻了一半：那时候
    // 清单是一行 flex 汤，表头无处可挂；现在它是 grid 真列，列头就是列头。
    // 「类型」那一列仍然**不做**——扩展名本来就在文件名里，doc_kind 是机器词（'company'）。
    "filesColName": "文件名",
    "filesColSize": "大小",
    "filesColChunks": "可引用片段",
    "filesColTime": "上传时间",
    "filesColStatus": "状态",
    // 手机上不摆列头（五列×两行的骨架里没有它的位置），所以片段数得自带单位，
    // 否则 18 是个无名数。短到能挤进第二行——长的那条是上面的 filesChunks。
    "filesChunksShort": "片段",
    "filesNoMatch": "没有文件名含「{q}」的。",
    // ── #77 · 删除文件。v1 没有这颗按钮是因为后端根本没有这个口子。────────────────
    // 🔴 销毁类：确认步不是装饰；正文必须说清**还有什么会跟着变**——删一份文档会重建
    // 记忆面，卡片上来自它的读数会失去出处。deleteError 照 downloadError 的碑：那个端点
    // 把「没有这份」和「你证明不了这是你的」编成同一个 404，前端一种都分不出来。
    "delete": "删除",
    "deleting": "正在删除…",
    "deleteConfirmTitle": "删掉「{name}」？",
    "deleteConfirmBody": "Avery 会忘掉这份文件里读到的全部内容。卡片上来自它的那些读数会失去出处。这一步撤不回来，要拿回来只能重新传一次。",
    "deleteConfirmAction": "确认删除",
    "deleteCancel": "先留着",
    "deleteError": "这份文件刚才没能删掉，再试一次。"
  },
  // partner-docs-0728 ·「文件与表单」页。M3 生成，2026-07-28。
  // 🔴 langNote 在中文下是**有意的空串**：那句话说的是「文件正文只有中文、页面外壳不是」，
  // 对中文读者没有意义。组件按空串跳过渲染，不要为了"两边对齐"给它编一句中文。
  "paperwork": {
    "title": "文件与表单",
    "lede": "公司先把这几份交过来，Avery 才派得上用场；边上再放几份配套协议。全都能下载——真正签、填的是文件本身，页面上的文字只是让你下载前先过一遍。",
    "langNote": "",
    "draftBanner": "先打个招呼：这是样本，不是定稿。还没送律师过目，最终条款以双方实际签署的那份为准。",
    "draftBadge": "草案",
    "formsHeading": "标准表单",
    "formsLede": "还在想该给 Avery 递什么？就是这些。填好之后，按平时上传文件的方式传过来就行。",
    "legalHeading": "协议草案样本",
    // M3 原句里是「App 里没有签章流程」；改成「产品里」是为了不给 verify-zh-purity 的
    // 拉丁词表加一个本来就有中文写法的词（那张表只该收 PDF/DPA 这类真专名）。语义未动。
    "legalLede": "几份草案，仅供讨论。签署走线下纸面，产品里没有签章流程——在这里点任何按钮，都不构成任何承诺。",
    "showNotes": "查看起草者的内部备注",
    "internalNoteTag": "内部备注 · 不属于协议正文",
    "expand": "展开全文",
    "collapse": "收起"
  },
  "team": {
    "emptyTitle": "你的团队会在这里长出来",
    "emptyBody": "把几个文件拖到右边——人和项目会从里头浮现，Avery 会带着一份能用的解读回来：哪里值得留意，哪里值得再看一眼。什么也不用配置。"
  },
  "nexus": {
    // ⚠ #79 · 这三条是**共享段**：v01 冻结壳的 RoomScreen（:133/134/186）与 v02 同用。
    //  改它们两壳一起变——但两壳此前就是同一句，改完仍是同一句，不制造「两壳分叉」。
    // ⚠ liveThinking 的新值**不是** recon §5 表里的「正在分析」：#75 之后 v02 的眉标只在
    //  `running` 时渲染（RoomScreen:399-401），照表改会让眉标「正在分析」与下面那行状态
    //  「正在分析…」逐字撞车、上下堆着说同一句话。这里改成**给这条状态条命名**（它是什么）
    //  而不是重复它的状态（它在干嘛）：容器 aria-label 也用这个键，四态下都不撒谎。
    "liveThinking": "实时进度",
    "liveRunning": "正在分析…",
    "liveReady": "分析完成",
    "liveError": "暂时连不上，再试一次？",
    // ⚠ HAND-WRITTEN, act-first（#75 · 议事室停止生成）：manager 自己按停之后的状态词。
    // 与 liveReady 互斥——改造前中止被收成 complete，屏上会写「分析好了，可以看了」，
    // 而他刚亲手按停。措辞刻意只说「没答完」，不说「已省下」：后端对客户端断开零处理，
    // 当前那一步 LLM 调用照样跑完，说省下就是撒谎。
    "liveInterrupted": "已停止，这轮没答完",
    "askPlaceholder": "向你的团队提问…",
    "ask": "提问"
  },
  "transport": {
    "misconfigured": "这个版本没配置好 —— 发布时没带上后端地址。重试没有用，需要重新构建后再发布一次。",
    "offline": "连不上服务器。检查一下网络，再试一次。",
    // #91 · deposit 超时熔断。🔴 超时 ≠ 失败：文件多半已经传上了、只是回执没送回来（0812 的
    // 病灶正是「服务端收完了、socket 已死」）。动词必须是「刷新看看」不是「重试」——
    // 抢先说失败会引导用户重传出第二份。⚠ HAND-WRITTEN（2026-08-03 口径：中文由 session 直写）。
    "depositTimeout": "等了很久没有回音——不过文件很可能已经传上了。先刷新一次，看看资料库里在不在，再决定要不要重传。",
    "rateLimited": "请求太频繁了，等 {seconds} 秒后再试。",
    "rateLimitedWait": "刚才请求有点多，稍等一会儿再试。",
    "tooLarge": "一次最多上传 10 个文件，单个不超过 10MB。",
    "unsupportedType": "这个文件类型不支持，或者里面的内容读不出来。",
    "staleToken": "这台浏览器的访问凭据没了 —— 公司数据还在，只是这台浏览器打不开它了。",
    "serverError": "服务器出了点问题（HTTP {status}）。稍后再试一次。",
    "generic": "出了点问题（HTTP {status}）。再试一次。"
  },
  "lite": {
    "tabTeam": "你的团队",
    "tabRoom": "议事室",
    "tabNotes": "Avery 的笔记",
    "tabPlaybooks": "操作手册",
    "tabVision": "未来方向",
    "groupAllLabel": "按团队分组",
    "groupUngrouped": "其他成员",
    "groupCollapse": "收起",
    "groupExpand": "展开",
    "groupCountOne": "人",
    "groupCountMany": "人",
    "roomCanvasHint": "拖动平移 · 滚动缩放",
    "roomCanvasReset": "重置视图",
    "playbooksEyebrow": "即将推出",
    "playbooksTitle": "操作手册从团队已有的工作方式中生长出来",
    "playbooksBody": "当 Avery 接入了你自己的 SOP、检查清单和过往决策后，会把它们提炼成可复用的操作手册——下次遇到类似情况，会议室已经知道你的行事规则。",
    "playbooksSlotRoster": "入职与交接的 SOP 自动转成一步步可执行的操作手册。",
    "playbooksSlotIncident": "反复出现的情况沉淀为固定打法，会议室每次都按同一套路走。",
    "playbooksSlotPack": "行业包（先从酒店业开始）会预置可直接套用的打法，你可以按需调整。",
    "playbooksSlotLabel": "这里会有什么",
    "playbooksComingSoon": "暂未接入——这里是 Avery 接下来会落地的方向预览。",
    "playbooksEmptyTag": "暂无操作手册",
    "visionEyebrow": "未来方向",
    "visionTitle": "你刚才试的是 demo。这背后才是产品。",
    "visionLede": "其它标签页里跑的一切，都基于你自己上传的文件。这是有意为之——这是最快的方式，让你感受到 Avery 是如何读懂一个团队的。真正的产品，比这再往前走一步。",
    "visionNowLabel": "你刚才用的",
    "visionNowTitle": "一份用你自己的文件驱动的 demo",
    "visionNowBody": "你丢进来一份花名册和一份计划，看着团队从中长出来，并向这间屋子提了一个真正的问题。这里没有为你写好的脚本——它读的是你给它的内容。这是一个公开的、可自助试用的版本，不是已部署的产品。",
    "visionRealLabel": "Avery 真正是什么",
    "visionRealTitle": "为一家公司量身打造的定制 agent",
    "visionRealBody": "在生产环境里，Avery 是为你的公司专门配置的——接入你自己的系统与文档，部署在你自己的安全环境内，而不是一个共享环境。它始终是一个聚焦的、领域专属的 agent，只认识你的团队，所以访问是有边界的、可审计的，而不是一个大模型到处伸手。",
    "visionProofLabel": "这份 demo 在证明什么",
    "visionProofTitle": "三件今天值得你判断的事",
    "visionProofUiux": "界面——一支团队、一场实时解读，动起来到底是什么手感。",
    "visionProofJudgment": "判断——这间屋子对一个真实情境的解读，是不是你愿意信的那种。",
    "visionProofRedline": "这道边界——Avery 能不能给人打分，是公司自己握着的一道开关，默认关着，要开得有人显式去拧。关着时，涉及给人打分的内容在入口就被挡回去；开着时，它会带着证据一起递进来，作为决策支持——但绝不单独构成人事决定的依据。",
    "visionMockEyebrow": "接入你的数据之后",
    "visionMockTitle": "这条边界打开之后的样子",
    "visionMockLede": "这些是预览，不是你现在可以点的功能。我们把它们摆出来，是希望你诚实地判断方向——每一项都已标注，不会有任何一项被误读为已经交付。",
    "visionTagPreview": "预览",
    "visionTagComing": "即将",
    "visionTagMock": "模拟",
    "visionMockFilesTitle": "agent 自己的文件空间",
    "visionMockFilesBody": "Avery 为每家公司保留一个独立的私密文件空间——存放你的文档、它的工作笔记，以及它产出的文件。这样一次解读可以在上一次的基础上继续，而不是每次都从零开始。",
    "visionMockSkillsTitle": "技能、工具与 SOP，皆为你而设",
    "visionMockSkillsBody": "你那些反复出现的工作——怎么入职、怎么做复盘、怎么处理卡住的项目——会变成一个有名字的技能，每次都以同样的方式跑。可预期是设计出来的，不是靠 prompt 即兴发挥。",
    "visionMockLoopTitle": "在你离开时也在跑的工作",
    "visionMockLoopBody": "把一批情境交给 Avery，它会在后台按自己的节奏逐个处理。你回来时看的是结果——不是一场需要盯着的实时会话。最稀缺的是你的注意力，所以产品把它留到最后用。",
    "visionMockGateTitle": "边界是闸门，不是愿望",
    "visionMockGateBody": "把一个团队读偏了，代价是补不回的信任。所以公司选定的「要不要给人打分」这个立场，不是提示词里一句聪明的请求就能绕开的话——而是在每条观察落库的入口，由一道确定性检查来强制执行。关着，涉及给人打分的内容直接被拒；开着，则连同证据一起放行。",
    "visionMockPersonName": "一位团队成员",
    "visionMockPersonRole": "读的是他做什么、扛什么——不是一个数字。",
    "visionComingSoon": "这四项目前都尚未上线。这个标签页是这条边界的预览，故意保持诚实。",
    "notesEyebrow": "实录笔记",
    "notesTitle": "Avery 记下的、关于你公司的观察",
    "notesLede": "每当你在议事室问一个真实的问题，Avery 都会用它自己的话把观察到的记下来，供你翻阅。你们合作得越久，这本笔记就越厚。",
    "notesRedlineNote": "这些笔记写的是工作本身——项目、交接、负荷。至于「会不会给人打分」，是公司握着的开关，不是一句聪明的提示词能翻动的；任何一条笔记都不能单独作为人事决定的依据。",
    "notesCountSince": "条观察 · 始于",
    "notesCountOne": "条观察",
    "notesCountMany": "条观察",
    "notesToday": "今天",
    "notesSourcePrefix": "来自你的提问：",
    "notesEmptyEyebrow": "还没有记录",
    "notesEmptyTitle": "Avery 还没写下第一条笔记",
    "notesEmptyBody": "去议事室问一个关于你团队的真实管理问题。当 Avery 注意到值得留存的东西——一个模式、一处风险、一条依赖——它就会记在这里。",
    "notesEmptyCta": "去议事室提问",
    "notesNudge": "Avery 记了一条笔记",
    "briefingEyebrow": "来自你上传的文件",
    "metricsLabel": "团队一览",
    "briefingHeadline": "你的团队：{people} 位成员，{projects} 个进行中的项目。",
    "briefingHeadlineFilesPartial": "读取了 {ingested}/{uploaded} 份文件：{people} 位成员，{projects} 个进行中的项目。",
    "briefingSubheadRisk": "以下内容全部来自你上传的文件，没有一处是编的。其中 {atRisk} 个项目值得多看一眼。",
    "briefingSubheadRiskItems": "以下内容全部来自你上传的文件，没有一处是编的。其中 {atRisk} 处值得多看一眼。",
    "briefingSubheadCalm": "以下内容全部来自你上传的文件，没有一处是编的。文件里没有读出风险信号。",
    "briefingMetricPeople": "位成员",
    "briefingMetricProjects": "个进行中的项目",
    "briefingMetricNeedLook": "个值得多看一眼",
    "handoffsTitle": "今天值得你留意",
    "handoffsEmpty": "暂时没有需要你出面的事——文件读起来一切平稳。",
    "handoffsEmptyButLook": "眼下没有需要你出手的事——不过有 {count} 处值得多看一眼。",
    "handoffOpen": "打开项目",
    "handoffToneLabel": "多看一眼",
    "handoffAction": "{project}：今天先过一下",
    "handoffEvidenceFallback": "文件里，{project}的状态标记为「{status}」。",
    "handoffEvidenceTag": "来自你上传的文件",
    "handoffStatusAtRisk": "有风险",
    "handoffStatusBlocked": "受阻",
    "personReadOwns": "负责：{items}",
    "personReadListSeparator": "、",
    "personReadNone": "团队成员",
    "personCardOpenAria": "打开{name}——{read}",
    "groupOwns": "负责：{project}",
    "streamNudgeRedline": "再核对一遍，只描述工作本身，不给任何人贴标签。",
    "streamNudgeChain": "先把回答落到证据上，再动手起草。",
    "streamAskDrafted": "一条快问已拟好，等你确认",
    "streamAdviceReady": "判读好了",
    "streamAdviceDone": "好了",
    "streamFailed": "连上议事室时出了点状况。",
    "streamErrorUnknown": "暂时没拿到失败详情。",
    "emptyEyebrow": "开始上手",
    "emptyHintRoster": "团队花名册或几份简历都可以——成员会以卡片形式出现。",
    "emptyHintProject": "项目计划或周报都可以——项目会排在他们旁边。",
    "emptyHintPrivacy": "给人打分这件事，是公司握着的开关——在打开之前，Avery 只记大家做了什么、在负责什么。",
    "peopleLane": "人员",
    "projectLane": "项目",
    "roomEmptyTitle": "把眼前的事带进议事室",
    "roomEmptyBody": "把团队里让你放心不下的事写下来——它会对照你上传的文件想清楚，再给你一份判断。",
    "refAll": "全部",
    "refPeople": "人员",
    "refProjects": "项目",
    "refAdd": "添加参考",
    "refSearch": "引用一位成员或一个项目",
    "refEmpty": "先上传几份文件——成员和项目会出现在这里。",
    "detailAria": "详情",
    "detailClose": "关闭",
    "detailPersonEyebrow": "团队成员",
    "detailProjectEyebrow": "项目",
    "projectsStatusBlocked": "受阻",
    "projectsStatusAtRisk": "有风险",
    "projectsStatusOnTrack": "按计划推进",
    "projectsStatusDone": "已完成",
    "projectsStatusUnknown": "状态未提及",
    "projectsUnknownValue": "文档未提及",
    "detailTenure": "在职时长",
    "detailOwns": "手上的事",
    "detailCollab": "协作中的伙伴",
    "detailSummary": "概览",
    "detailProgress": "进展",
    "detailBlockers": "值得再看一眼",
    "detailSignals": "文件里提到的",
    "detailGone": "这张卡片已不在你上传的文件里。",
    "adviceCardAria": "它看到了什么 —— 判读",
    "adviceEyebrow": "它看到了什么",
    "roomAnswerLabel": "Avery 的回答",
    "adviceReadTitle": "判读",
    "adviceSignOff": "由你拍板",
    "adviceSummaryAria": "摘要 —— 判读",
    "adviceSignalsLabel": "事实——它捕捉到的信号",
    "adviceHypothesesLabel": "推断——可能在发生什么，不是定论",
    "adviceMostLikely": "最可能的情况",
    "adviceAlsoPossible": "也存在这种可能",
    "adviceBackingLabel": "依据",
    "adviceEvidenceLabel": "事实——这条意见所依据的原文行",
    "adviceConfidenceLabel": "置信度——它有多确定",
    "adviceConfidenceWouldChange": "什么会让判读改变",
    "adviceMoveLabel": "下一步",
    "adviceActionsLabel": "建议——推荐的下一步动作",
    "adviceScriptLabel": "如果你要开 1:1",
    "adviceWatchLabel": "看什么来判断奏效了",
    "adviceHrAria": "HR / 谁来把关",
    "adviceHrLabel": "何时拉上 HR",
    "adviceEscalationNotYet": "暂时不用",
    "adviceConfirmsLabel": "谁来把关",
    "adviceConfidenceLow": "较低",
    "adviceConfidenceMedium": "中等",
    "adviceConfidenceHigh": "较高",
    "adviceEscalationHRBP": "人力伙伴",
    "adviceEscalationLegal": "法务",
    "adviceEscalationWellbeing": "员工关怀",
    "adviceEscalationCompensation": "薪酬",
    "adviceEscalationExecutive": "高管层",
    "topbarAria": "Avery 控制栏",
    "screenNavAria": "屏幕导航",
    "composerAskAria": "就你的团队提问",
    "composerRefsAria": "引用资料",
    "composerRemoveRefAria": "移除 {label}",
    "composerFilterAria": "筛选引用资料",
    "roomBoardAria": "议事室 —— 看板",
    "terminalAria": "Avery 的推理过程",
    "roomAskAria": "向你的团队提问",
    "roomLiveQuestionAria": "当前提问",
    "roomEmptyAria": "还在梳理中 —— 向你的团队提问",
    "notesEmptyAria": "Avery 的笔记 —— 暂无内容",
    "playbooksEmptyAria": "操作手册 —— 即将上线",
    "teamLiveAria": "你的团队 —— 实时",
    "projectsOpenAria": "打开 {title}",
    "terminalTitle": "它是怎么想明白的",
    "roomToolLabel": "工具",
    "roomManifestLabel": "结果"
  },
  "lite2": {
    "tabTeam": "团队",
    // ⚠ #79 · Danny 2026-08-09 逐条勾选时**亲自推翻**自己 07-29 的定名（ADR-0031「问 Avery」）：
    //  tab 主名改「对话」。不是笔误，别劝回、别顺手改回去。
    //  连带纪律（本票立的碑）：**名字引用**跟着改（followupsSourceRoom / homeTodayEmpty /
    //  followupsEmptyActive / roomBoardAria / formsBuilderGoesToLibrary），**动词短语不改**
    //  （「去问 Avery」是动作不是屏名；悬浮胶囊 askAveryLabel 仍叫「问 Avery」，同 Claude 的
    //  「Claude 是谁 / Chats 是哪儿」分工）。EN 取更短的 `Chat`（tab 宽度闸只许等长或变短）。
    "tabRoom": "对话",
    "tabPlaybooks": "操作手册",
    "tabVision": "完整版预告",
    "tabFollowups": "待办清单",
    "tabFollowupsSub": "跟进",
    // #63（merge-closerlook）：tabCloserLook 已退休——「值得注意」屏并进「今天」的差距摘要块，
    // 对照卡文案（下面 gap* 键族）原样活着，死掉的只有 tab 名。
    "tabNotes": "Avery 的笔记",
    // ⚠ HAND-WRITTEN, NOT YET M3（files-hub-0729/01 · ADR-0032）：资料库屏。按 PRD
    // 「en 源 → zh 导演手改，短键先例」办。词族锁定见 scripts/i18n-zh-lite2-delta.mjs 的铁律 4：
    // 文件这一族统一说「资料」——页名「资料库」与首页板块「资料概览」同词族，不混用
    // 「文档/档案/文件库/知识库」。
    // 🔴 filesCurrentEmptyRead 同样不许说「你的文件没了」：清单为空只说明我们没读到，
    // 不等于客户那边没有（本轮总纪律 absent≠none）。
    "tabFiles": "资料库",
    "filesEyebrow": "资料库",
    // #84 ·「双标题收成一层」：filesHeading / filesSub 两条随本票**从两份字典删掉**——
    // 改造前 eyebrow + h2 + 副标 + 小节标题 +「你的文件」五层标题说同一件事（病根之一）。
    // 现在页头只有一行：分区名 + 有多少。
    // ⚠ filesCurrentTitle 改口成「文件」：它现在是**左栏那一行**的标签（也是工作台页头的
    //   标题），不再是长条上的小节名。词族锁（文件这一族统一说「资料」）仍守在**页名**上
    //   ——「资料库」；行名跟着 `upload.filesTitle`（你的文件）走，两处同词。
    "filesCurrentTitle": "文件",
    "filesCurrentEmptyNone": "还没传过资料。用上面的「上传文件」发几份给 Avery，团队信息就会整理出来。",
    // 🔴 #86 欠账②：这句原来写的是「多半是这些文件没读出内容，重新传一次最快」——#86 之后
    // 「有档案、零文件」变成一个**用户亲手造得出来**的状态（清空），那句诊断当场变成假话：
    // 把一次成功的销毁说成一次解析失败。改成不替用户断言是哪一种（absent≠none 的同一条纪律），
    // 三种可能都摆出来，出路只有一条、说清楚就够了。
    "filesCurrentEmptyRead": "这份档案里现在没有文件。刚传完的话稍等一下再刷新；也可能是你清空过，或者上一批没读出内容——不管哪种，用「上传文件」再传一批就能接着用。",
    // 刚刚亲手清空的那一下，值得一句确定的话（上面那句要照顾三种可能，所以只能含糊）。
    "filesCurrentEmptyCleared": "这份档案已经清空了。链接、登录、发出去的表单都照旧能用，随时可以重新开始传。",
    // ⚠ HAND-WRITTEN, NOT YET M3（T10 · 补资料）。
    // #84 · filesAppendTitle / filesAppendLede 随本票删掉：补资料不再是一个独立小节，
    //   它就是文件工作台工具条上那颗「上传文件」（有档案时它天然是 append 那条路）。
    // 🔴 demoNote 留着：它说的是「为什么这儿传不进去」，不是「这个功能不存在」——示例副本
    //    本来就是随手可弃的，往里补资料会随清理一起没，那才是真正该讲清楚的一句。
    // 🔴 #88 收尾修：这句原文指着「在左栏的『新建一家公司』里建一家」——而那块**正是 #88 撤掉的**。
    // 机制那半 #88 修了（`empty_context` 清 `ephemeral` = 清空即认领），文案这半漏了，
    // 于是它在生产上指挥用户去点一个不存在的按钮（0810 上产后复验逮到）。
    // 现在指向真实出路：左栏最底那一条。
    "filesAppendDemoNote": "示例团队是一份随时会被清理掉的副本，往里补的资料留不住。要把它变成你自己公司的档案，用左栏最底的「清空这份档案」——清空之后这份档案就归你了，可以开始传你们自己的文件。",
    // ── #84 · 两栏 file explorer 的壳 ───────────────────────────────────────────────
    "filesRailMore": "其他",
    "filesRailScrimAria": "关掉资料库分区栏",
    "filesUploadAction": "上传文件",
    // 🔴 刻意**不写**「在这些文件里找…」（原型上那句）：那句话许诺的是全文检索，而后端没有
    // 这个端点——我们只对得起文件名这一层。说大了就是假按钮的文案版。
    "filesFilterPlaceholder": "按文件名筛…",
    "filesCountLine": "{n} 份 · 共 {size} · {chunks} 处可引用片段",
    "filesDropHint": "把文件拖到这块工作台的任意位置就能加进来 · 支持",
    // ── #84 ·「清空这份档案」（#86 的 UI 挂点）────────────────────────────────────
    // 🔴 三段分开写，不合并：「员工已经交上来的答卷留着」这句最容易被跳读，而它恰恰是用户
    //    清空之后最可能来投诉的一件事（答卷重新归档时，读出来的东西会再次出现在资料库里）。
    // 🔴 措辞照后端 `empty_context` 的 docstring 逐条对表，不许多说也不许少说。
    "filesEmptyEntry": "清空这份档案…",
    "filesEmptyTitle": "清空这份档案？",
    "filesEmptyBodyGone": "会删掉：你传过的全部文件（原件也删），以及 Avery 从这些文件里读出来的人、项目、信号、矛盾——全部。删掉的文件找不回来。",
    "filesEmptyBodyKept": "会留下：你和 Avery 的对话记录、Avery 自己写的观察笔记、常驻表单，以及员工已经交上来的答卷（那是他们的话，而且你发出去的填写链接还在生效）。",
    "filesEmptyBodyStays": "这份档案本身不会消失——链接、登录、已经发出去的表单都照旧能用，你可以立刻重新开始传。之后如果把某份答卷重新归档，它读出来的东西会再次出现在资料库里。",
    "filesEmptyConfirmLabel": "确认请输入「{word}」",
    // 🔴 手打一个词才放行。这个词必须**真的存在于屏幕上**：#86 回执草稿写的是「输入店名」，
    //    但这个应用里根本没有店名这个字段（KnownContext 只有 id/files/at），要求用户输入一个
    //    不存在的字符串 = 一道谁也过不去的门。
    "filesEmptyConfirmWord": "清空",
    "filesEmptyAction": "确认清空",
    "filesEmptyCancel": "先留着",
    "filesEmptyBusy": "正在清空…",
    "filesEmptyError": "刚才没能清空，什么都没删。再试一次。",

    // ── #85 ·「这次补料改了什么」只读流水 ───────────────────────────────────────────────
    // ⚠ HAND-WRITTEN（本 session 直接定稿，不走 M3 —— 口径 2026-08-03 已改）。
    // 🔴 这一区的全部分寸都在拍板③（2026-08-07「补传后安静更新、不打扰」）与拍板 B
    //    （「事后要查得到」）之间：**不弹通知、不占今天页**，只在这里可查。所以第一句话就把
    //    「Avery 已经自己改好了」说在前面——把它写成一堆待办，就是把拍板③ 又推翻一次。
    // 🔴 词族锁：这一族统一说「资料」（同页名「资料库」），不说「文档/档案/知识库」。
    // 🔴 不许出现「冲突/矛盾/异常」那一族词：那是今天页决策卡的活，这里只是流水账。
    "changesTitle": "资料更新",
    "changesLede": "你补上新资料之后，Avery 会直接把卡片改成新的说法，不来打扰你。改了哪些、依据是哪一份，都记在这儿。",
    "changesCountLine": "{n} 处改动 · 来自 {files} 份资料",
    // 🔴「没有」与「还没发生过」是两件事，但对用户来说出路一样：这句只说事实 + 出路，
    //    不替他断言是哪一种（同 filesCurrentEmptyRead 那条纪律）。
    "changesEmpty": "还没有这样的记录。等你再传一批资料进来，Avery 顺着新资料改动过的地方就会列在这里。",
    "changesEmptyHint": "第一次上传不算「改动」——那时候所有卡片都是新读出来的。",
    // 每一行：主体 + 哪一格 + 从什么变成什么。三段分开渲染，不拼成一句长话。
    "changesFieldOf": "{subject} · {field}",
    "changesFilled": "补上了",
    "changesAddedPerson": "新增同事「{subject}」",
    "changesAddedProject": "新增项目「{subject}」",
    "changesFromDoc": "依据《{doc}》",
    "changesFromDocLine": "依据《{doc}》第 {line} 行",
    // 引文可点：跳到「文件」那一区并按这个文件名筛出来。**做不到的不许许诺**——我们没有
    // 原文阅读器，点不到具体那一行，所以 aria 里说的就是「在文件里找到它」。
    "changesJumpAria": "在文件里找到《{doc}》",
    "changesMarkRead": "已查阅",
    "changesUnmark": "取消标记",
    "changesReadFold": "已查阅（{n}）",
    // 列表项的分隔符（顿号）。中英不同，所以它是一条键、不是写死在代码里的字符。
    "changeListJoin": "、",
    "changeFieldRole": "职位",
    "changeFieldTeam": "部门",
    "changeFieldTenure": "司龄",
    "changeFieldOwns": "负责",
    "changeFieldCollaboration": "协作",
    "changeFieldOwner": "负责人",
    "changeFieldStatus": "状态",
    "changeFieldDueDate": "截止",
    "changeFieldSummary": "简介",
    "changeFieldProgress": "进度",
    "changeFieldRisk": "风险",
    "changeFieldMilestones": "里程碑",
    "changeFieldBlockers": "卡点",

    // ⚠ HAND-WRITTEN（gap-design-0805 T3 · form-frontend-a1c）：资料库第④段「常驻表单」。
    // 词族锁定：这一族统一说「表单」，不混用「问卷/表格/打卡/考勤」。
    // 🔴 表单是**员工本人对自己这段工作的说法**，不是对人的评分——后端 gate_form_red_line
    // 连一张给人打分的题面都拒绝落库。所以打分/排名/考核/绩效那一族词一个都不许出现。
    // 🔴「转发」照实说是经理自己做的事：服务端不发消息、不碰 IM（拍板 #4）。不许写成
    // 「已发送给他」这种把人的动作说成系统动作的话。
    // 🔴 三条铸链失败各自一句：复用 transport.* 通用句会在人数越界（422）时对经理讲文件
    // 格式（理由见 store.ts 的 FormsMintError）。
    "formsTitle": "常驻表单",
    // ⚠ #84 改了指路：清单不再在「上面」，它在左栏的「文件」那一区。
    "formsLede": "给每个人生成一条链接，你自己转发过去；他在手机上填完，内容就成为左栏「文件」里的一份，原话照录、标明是他自己说的。",
    // #84 · 拼装器挪到这一区最后（很少动），前面加一行小标把它和上面的铸链分开。
    // 「改表」不是「编辑模板」：经理心里那件事是"把这张表改一改"，不是在管理一个模板对象。
    "formsEditTitle": "改表",
    // 🔴 分隔符写进字符串本身，不写在 JSX 里：初版是 `{l.formsFieldsLead}：{preview}`，
    // 那个全角冒号硬编码在组件里，英文壳上就多出一个中文标点，而 i18n 门看不见它
    //（它扫的是这份文件里的键，不是 tsx 里的字面量）。
    "formsFieldsLead": "会问这几题：",
    "formsPickLabel": "这次发给谁",
    "formsPickHint": "点名字选中，一次最多 30 个人。每人一条自己的链接，谁也看不到别人写了什么。",
    // 绑项目（0807 HITL 补的入口）。措辞刻意是「关于哪个项目」而不是「归属/分配」——
    // 绑的是这份周报**在说哪件事**，不是把人派给项目。
    "formsBindLabel": "这几份周报各自关于哪个项目",
    "formsBindHint": "选了项目，他在「未达成及原因」里写的原话才会带着出处进那张项目卡；不选就只进他自己的人卡。",
    "formsBindNone": "不绑项目",
    "formsStatusAbout": "关于 {project}",
    "formsMintAction": "生成本期链接",
    "formsMintBusy": "正在生成…",
    "formsLinksTitle": "{period} 的链接",
    "formsLinksNote": "链接由你自己转发给本人——Avery 不替你发消息。一人一链，七天过期，交完就锁上。",
    "formsCopy": "复制",
    // #76 · 30 个人就是 30 轮「复制→切微信→粘贴→回来」。逐行那颗保留，这颗是加法；
    // 🔴 必须自己一份 state：逐行的 copiedId 是**单值**，复用会把某一行误点亮成「已复制」。
    // #76 · 四种静默蒸发形态给可见降级。这一条管「表单没拉到」——今天 token 失效与
    // 「这条通道没有这个功能」长得一模一样：整段无声消失，一个字都不说。
    "formsUnavailable": "这会儿没能读到你的表单。东西没丢，刷新一下再看。",
    "formsCopyAll": "复制全部链接",
    "formsCopiedAll": "已复制 {count} 条",
    // 剪贴板会被拒（无 https / 无权限）。逐行那条按设计静默（URL 恒可见可选），
    // 批量这颗不行——屏上什么都不变，经理会把上一次的剪贴板内容粘出去。
    "formsCopyAllFailed": "没能复制。上面每条链接都可以手动选中。",
    "formsCopied": "已复制",
    "formsStatusTitle": "谁交了",
    "formsStatusOpen": "还没交",
    "formsStatusSubmitted": "已交",
    "formsStatusExpired": "链接过期了",
    // absent≠none 在这一格：不认识的状态词就说「状态未知」，绝不悄悄按好的那几种渲染
    //（同 fileStatusUnknown 的纪律）。
    "formsStatusUnknown": "状态未知",
    "formsErrorRejected": "这次没生成成。一次发给 1 到 30 个人，改完再试一次。",
    "formsErrorRetired": "这张表已经撤下了，不再发新链接。",
    "formsErrorFailed": "这会儿没能生成链接。过一会儿再试。",
    // T9（gap2 #58）· 自动补铸 + 撤回。
    // 🔴 措辞把「照抄的是你上期自己选的名单」说明白——这是它不算替经理断言的**理由**，
    // 不写出来，经理看到的就是「系统自作主张给一群人发了东西」。
    // 「下面可以改」不另做跳转按钮：改的入口（选人那排、每行的撤回）就在同一屏往下一点。
    "formsAutoFilled": "{period} 的链接已经按你上期发过的名单备好了（{count} 人）。要换人、要撤掉谁，下面就可以改。",
    "formsVoid": "撤回",
    "formsVoiding": "正在撤回…",
    // 无障碍名：一排「撤回」按钮在读屏器里全都叫「撤回」，说不出撤的是谁那一条。
    "formsVoidAria": "撤回发给{name}的这条链接",
    // ⚠ HAND-WRITTEN（gap2 T11 · 模板拼装器）。词族仍锁在「表单」，不混用问卷/表格/打卡。
    // 🔴 三个开关旁边必须说清这一格的答案**去哪儿**。没勾开关的题照旧逐字进资料库
    //（可检索、议事室引得到），只是不长成卡——绝不暗示「加一个字段就会自动长出一张卡」。
    // 🔴 一个字都不许往「给人打分」上靠：写侧红线门连一张打分的题面都拒绝落库，
    // 任何邀请经理那么写的文案都是一句产品做不到的承诺。
    // 🔴 这里只放界面文案。经理自己打的表名/题面/说明/选项是**客户的内容**（与文件名同级），
    // 一个字都不进词典。
    "formsBuilderNew": "建一张表",
    "formsBuilderCopy": "照「{title}」改一张",
    "formsBuilderEdit": "改「{title}」",
    "formsBuilderEditing": "正在改「{title}」",
    "formsBuilderNewTitle": "新建一张表",
    "formsBuilderDraft": "让 Avery 读一份你们的旧表格",
    "formsBuilderDraftBusy": "正在读…",
    "formsBuilderDraftHint": "挑一份你已经传上来的文件。Avery 把它的表头变成题目——你不点保存，什么都不会存下来。",
    "formsBuilderDraftFromLlm": "根据 {filename} 起草的。保存前自己过一遍。",
    // 诚实降级：模型没参与的时候，不许讲成「Avery 读懂了你的表」。
    "formsBuilderDraftFromHeadings": "照 {filename} 的表头抄下来的——Avery 没有理解它们。",
    "formsBuilderDraftReview": "这些题目只是提案。要等你保存这张表、再生成链接，才会发出去。",
    "formsBuilderTitleLabel": "表名",
    "formsBuilderQuestionN": "第 {n} 题",
    "formsBuilderKind": "答题方式",
    "formsBuilderKindText": "自己写一段",
    "formsBuilderKindChoice": "从几个选项里挑一个",
    "formsBuilderKindNumber": "填一个数",
    "formsBuilderKindYesno": "是或否",
    "formsBuilderRequired": "必须回答",
    "formsBuilderChoices": "选项",
    "formsBuilderChoiceN": "第 {n} 个选项",
    "formsBuilderAddChoice": "加一个选项",
    "formsBuilderDropChoice": "去掉",
    "formsBuilderMin": "最小",
    "formsBuilderMax": "最大",
    "formsBuilderHelp": "题目说明（可选）",
    "formsBuilderSwitchSituational": "这题问的是哪儿卡住了",
    "formsBuilderSwitchLoad": "这题问的是他自己觉得有多忙",
    "formsBuilderSwitchMood": "这题问的是他自己的状态",
    "formsBuilderGoesToCard": "这一格的答案还会上他的人卡，带着一条能点回原话的出处。",
    // 🔴 #79 真 bug①：「议事室」是 v01 冻结壳的 tab 名，v02 里根本没有这个地方（全 lite2 段
    //  仅此一处泄漏）。改成 v02 的屏名（本票同时把它从「问 Avery」改成「对话」）。
    //  ⚠ G9 钉的是「只进资料库」与「不上任何卡」两个片段（verify-form-builder.mjs:122），逐字保留。
    "formsBuilderGoesToLibrary": "这一格的答案只进资料库——搜得到、在对话里引得到，但不上任何卡。",
    "formsBuilderRetire": "以后不问这一题了",
    // 这一句是「这里为什么没有删除键」的答案。
    "formsBuilderLockedHint": "已经有人答过这一题了，所以它得留在表上——留着，他那句答案才说得清自己在回答什么。",
    "formsBuilderDropField": "去掉",
    "formsBuilderAddField": "加一题",
    "formsBuilderCount": "{max} 题里用了 {asked} 题",
    "formsBuilderRetireForm": "撤下这张表",
    "formsBuilderRetireFormHint": "撤下之后不再发新链接。已经交上来的内容照旧在资料库里。",
    "formsBuilderSave": "保存这张表",
    "formsBuilderSaveBusy": "正在保存…",
    "formsBuilderCancel": "取消",
    // 🔴 与 formsError* 分成两族：同一个 422 在这两件事上意思完全不同，
    // 保存失败之后接一句「一次发给 1 到 30 个人」就是对经理撒谎。
    "formsBuilderErrorRejected": "Avery 没有收下这张表。它给的原因是：",
    "formsBuilderErrorUnavailable": "要先连上你的工作区才能建表。",
    "formsBuilderErrorUnreadable": "那份文件读不出来，没有可起草的东西。",
    "formsBuilderErrorFailed": "这会儿没能保存。过一会儿再试。",
    // 上限镜像（formShape.ts）。每一条都用**题号**指路——那正是编辑器里每一格标着的那个数。
    // `q3` 这种内部键经理从没见过，拿它指路等于没指。
    "formsIssueTitleMissing": "这张表还没有名字。",
    "formsIssueTitleTooLong": "表名超过了 {max} 个字。",
    "formsIssueNoQuestions": "一张表至少要问一题。",
    "formsIssueTooManyQuestions": "一张表最多问 {max} 题，这张问了 {got} 题。",
    "formsIssueTooManyStored": "这张表连停用的一起算，超过了 {max} 题。",
    "formsIssueDuplicateId": "第 {at} 题和前面某一题用了同一个内部键。",
    "formsIssueLabelMissing": "第 {at} 题还没写题目。",
    "formsIssueLabelTooLong": "第 {at} 题超过了 {max} 个字。",
    "formsIssueHelpTooLong": "第 {at} 题下面那行说明超过了 {max} 个字。",
    "formsIssueChoiceCount": "第 {at} 题要给 {min} 到 {max} 个选项，现在有 {got} 个。",
    "formsIssueChoiceEmpty": "第 {at} 题有一个选项是空的。",
    "formsIssueChoiceTooLong": "第 {at} 题有个选项超过了 {max} 个字。",
    "formsIssueChoiceDuplicate": "第 {at} 题有两个一样的选项。",
    "formsIssueNumberRange": "第 {at} 题的最小要小于最大，而且都落在 {floor} 到 {ceil} 之间。",
    "formsIssueSituationalKind": "只有让人自己写一段的题才谈得上「哪儿卡住了」，第 {at} 题不是。",
    "formsIssueLoadKind": "「有多忙」是一个数，第 {at} 题不是。",
    "formsIssueLoadRange": "「有多忙」在人卡上按百分比显示，所以第 {at} 题得是 0 到 100。",
    "formsIssueMoodKind": "「状态」是从几个词里挑一个，第 {at} 题不是。",
    "formsIssueSlotTaken": "第 {other} 题和第 {at} 题都想占人卡上同一个位置。",
    // ⚠ HAND-WRITTEN（files-hub-0729/03）：团队屏零文件元素 + 入口铺设。
    // 🔴 teamEmptyBody 说的是「我们还没拿到东西可读」，不是「你们没有团队」——
    // absent≠none 在这一格的样子。
    // teamEmptyLead = v02 版的 team.emptyBody。共用那句写的是「拖到右边」，v01 仍然为真
    // （它的团队屏还留着上传口），v02 撤走之后就成了假话——所以在这儿分叉，不改共用键。
    // ⚠ #79 · **新键**：v02 版的 `team.emptyTitle`。见仁见智⑥（「长出来」隐喻族）拍板时
    //  recon 把它记成「v01/共享段 3 处，随冻结壳不动」——**那个归类是错的**：
    //  `t.team.emptyTitle` 同时渲染在 src/lite/screens/TeamScreen.tsx:218 **和**
    //  src/lite2/screens/TeamScreen.tsx:362，也就是说那句「会在这里长出来」一直印在
    //  v02 团队空态的 h1 上（本票重冻的 team-desktop 基线里肉眼可见）。
    //  不改共享键、在 lite2 这边分叉——与紧邻的 teamEmptyLead 同一条先例、同一个理由。
    "teamEmptyHeadline": "你的团队会出现在这里",
    "teamEmptyLead": "等 Avery 读过你的几份文件——一份花名册、一份计划、几篇周报——人和项目就会出现在这里。什么也不用配置。",
    "teamEmptyTitle": "还没有可读的资料",
    // ⚠ #79 见仁见智⑥「长出来」隐喻族：只换掉隐喻那半句，**末句逐字保留**——那是 absent≠none
    //  红线本身（§6.1 点名不许动的语义），换隐喻不许把它一起改写。
    "teamEmptyBody": "这一屏的内容来自 Avery 读过的资料——一份花名册、一份计划、几篇周报。现在还什么都没进来，所以没有团队可显示。这说的是 Avery 手上有什么，不是你们公司有什么。",
    "teamEmptyCta": "去资料库",
    "homeFilesLink": "资料库",
    "homeFilesManageLink": "管理资料",
    "langSwitchAria": "语言",
    "langSwitchZh": "中文",
    "langSwitchEn": "英文",
    "lookSwitchAria": "观感",
    "settingsAria": "设置",
    // ⚠ #79 · 见仁见智②拍板：皮肤名从品牌语汇改大白话。`look` 的取值（paper/aurora）、
    //  URL 参数、data-look、localStorage 一个字节没动——改的只是这两颗按钮的标签。
    //  🔴 recon §4 写着「verify-switchers 读 URL 参数不读文本 → 门不红」，**那条转述是错的**：
    //  verify-switchers.mjs:74/86 有两条硬判据直接比对按钮文本，rich-align-0722/verify-restart-09.mjs:56
    //  还拿 /暖纸|Paper/ 找按钮。三处已在同一 commit 里同步。
    "lookSwitchPaper": "浅色",
    "lookSwitchAurora": "深色",
    // rich-align-0722/09 · 3 键手写 draft 待 Danny 审字（同 01-08 手写键口径）。
    "restartAction": "重新开始",
    "restartConfirm": "确认重新开始？",
    "restartAria": "重新开始——清空本设备上的全部内容并回到开头",
    // partner-docs-0728 · 设置菜单第四行（追加在末尾，不动上面三行）。M3 生成，2026-07-28。
    "settingsPaperworkLabel": "文件与表单",
    "settingsPaperworkLink": "标准表单与协议",
    // ⚠ HAND-WRITTEN（files-hub-0729/01 · ADR-0032）：设置菜单第五行——「完整版预告」从 tab
    // 降到这里。link 文案与 tabVision 逐字相同（"完整版预告"），入口换了地方、叫法不换，
    // 否则用户会以为是另一个页面。
    "settingsVisionLabel": "完整版",
    "settingsVisionLink": "完整版预告",
    "authSignIn": "登录",
    "authAccount": "账号",
    "authTitle": "账号",
    "authEmailLabel": "邮箱",
    "authPasswordLabel": "密码",
    "authDoSignIn": "登录",
    "authSignOut": "退出登录",
    "authWorking": "处理中…",
    "authGuestNote": "不登录也能用。登录后上传的数据会记在你名下，换设备也能打开；登录前传的那份，要在这里点一下「绑定到我的账号」才归你。",
    "authSignedInAs": "已登录",
    "authClaimTitle": "当前这份公司数据还没归到账号名下",
    "authClaimAction": "绑定到我的账号",
    "authClaiming": "绑定中…",
    "authClaimed": "已绑定到你的账号",
    "authClaimFailed": "绑定失败，稍后再试",
    "authRestoreFailed": "取不到你名下的公司数据",
    "authRetry": "重试",
    "groupCollapse": "收起",
    "groupExpand": "展开",
    "followupsEyebrow": "跟进",
    "followupsTitle": "所有要跟进的事都在这里",
    "followupsGroupToday": "今天",
    "followupsGroupWeek": "本周",
    "followupsGroupLater": "稍后",
    "followupsActiveTab": "进行中",
    "followupsHistoryTab": "已完成",
    // ⚠ 原文写「今早清单」——界面上没有任何东西叫这个名字，那一块叫「今日提醒」。
    "followupsEmptyActive": "还没有待跟进的事。可以在下面直接加一条，或者从今日提醒、对话、快问里加过来。",
    "followupsEmptyHistory": "还没有已完成项——做完的事会落到这里。",
    "followupsSourceTriage": "来自今日提醒",
    "followupsSourceRoom": "来自对话",
    "followupsSourceAsk": "来自快问",
    // #63：source id 'closer-look' 不变（已落盘的旧条目终身带着它），标签改指卡片现在住的块。
    "followupsSourceCloserLook": "来自「资料对不上的地方」",
    "followupsSourceManual": "你手动加的",
    "followupsSourceDecision": "来自一条决策",
    "followupsAddTitlePlaceholder": "要跟进什么？",
    "followupsAddGroupLabel": "时间",
    "followupsAddSubmit": "加到待办",
    "followupsDone": "完成",
    "followupsRestore": "恢复",
    "followupsDelete": "删除",
    "followupsEdit": "编辑",
    "followupsSave": "保存",
    "followupsCancel": "取消",
    "followupsDraftMail": "起草消息",
    "followupsCompletedAt": "已完成",
    "followupsTitleAria": "跟进标题",
    "followupAdded": "已添加",
    "adviceAddFollowup": "加到待办",
    // #63（merge-closerlook）：独立屏退休，对照卡搬进「今天」差距摘要块的展开态；
    // 页头三键（gapPageEyebrow/Title/Body）随屏死掉，下面的卡片/动作/历史/空态/预告键原样搬家。
    "gapCardClaimLabel": "文件里的说法",
    "gapCardEvidenceLabel": "资料里的实际情况",
    "gapOwnerPrefix": "负责人",
    "gapResolveLabel": "已核实",
    "gapDismissLabel": "先放一放",
    // 🔴 #79 真 bug④（本票新查出来的，recon 只把它列进「tab 改名连带」没说破）：这颗按钮的
    //  handleGapAsk（HomeScreen.tsx:236-249）走的是 setComposerHint + goScreen('room')——
    //  它把你带去问 **Avery**，一个字都不会发给那个人。「直接问本人」是界面在撒谎。
    "gapAskLabel": "去问 Avery",
    "gapAddFollowupLabel": "加到待办",
    // #63：这个动作铸出的待办标题。原屏写死英文模板（记档过的债），搬家顺手入字典。
    // 🔴 #79 真 bug②：「多看一眼」是 v01 冻结壳的词，v02 全站是「值得注意」（ADR-0031）。
    //  这条铸出来的待办标题会**永久落进 localStorage**，改晚一天就多一批带旧词的历史待办。
    //  ⚠ G4 钉的「多看一眼」只作用于 `.lite-handoffs-empty` 的文本（verify-handoffs-empty-honesty.mjs:105
    //  按壳分词），与本键无关 → 门不红。新值取动作句而不是「值得注意{title}」：待办要能读成一件事。
    "gapFollowupTitle": "确认一下{title}",
    "gapHistoryToggleLabel": "已处理的",
    "gapResolvedBadge": "已核实",
    "gapDismissedBadge": "已搁置",
    "gapRestoreLabel": "恢复",
    // ⚠ 原文与「今日提醒」的 handoffToneLabel「值得注意」撞词——经理会以为今日提醒也空了。
    //  新值与同块标题 homeGapsTitle「资料对不上的地方」同词；G6（snippet BANNED_TERMS）
    //  禁的是「差距/现实差距/gap/Nexus」，「对不上」不在表里 → 门不红。
    "gapEmptyTitle": "暂时没有对不上的地方",
    "gapEmptyBody": "等项目自报的进度和它遇到的卡点说法不一致时，会出现在这里。",
    "gapRealtimeTitle": "接上你们的系统之后",
    "gapRealtimeBody": "此刻它读的是你已经上传的文件。接上你们公司的数据源后，这个页面就变成了实时视图——报告和现实之间的偏差会自己浮现，不用等下一次上传。",
    // ⚠ #79 · 见仁见智③拍板改标题。eyebrow 同时从「观察记录」改成「笔记」是本票裁量：
    //  NotesScreen:153-154 把 eyebrow 与 h2 上下贴着渲染，新标题以「观察记录」结尾——
    //  不改 eyebrow 就是 §3.3 给 Files 治过的同一种「同一屏连着说两遍」。「笔记」与 tab 名同族。
    "notesEyebrow": "笔记",
    "notesTitle": "Avery 关于你公司的观察记录",
    "notesLede": "每次你问 Avery 一个真实的问题，它都会把观察到的记下来，供你回看。用得越久，这里的内容越多。",
    "notesRedlineNote": "这些笔记写的是工作本身——项目、交接、负荷。至于「会不会给人打分」，是公司握着的开关，不是一句聪明的提示词能翻动的；任何一条笔记都不能单独作为人事决定的依据。",
    "notesCountSince": "条观察 · 始于",
    "notesCountOne": "条观察",
    "notesCountMany": "条观察",
    "notesToday": "今天",
    "notesSourcePrefix": "来自你的提问：",
    "notesEmptyEyebrow": "还没有记录",
    "notesEmptyTitle": "Avery 还没写下第一条笔记",
    "notesEmptyBody": "去问 Avery 一个关于你团队的真实管理问题。当 Avery 注意到值得留存的东西——一个模式、一处风险、一条依赖——它就会记在这里。",
    "notesEmptyCta": "去问 Avery",
    "notesNudge": "Avery 新记了一条",
    "playbooksEyebrow": "即将推出",
    // ⚠ #79 见仁见智⑥：lite2 段的「长出来/生长出来」隐喻族共 6 处（本行 + filesCurrentEmptyNone /
    //  teamEmptyBody / playbooksLibraryTitle / visionNowBody / projectsLede），统一换「来自 / 整理出来」。
    //  v01 段与共享 team.emptyTitle 那 3 处随冻结壳纪律**不动**（zh.ts:313/361/374 一带）。
    "playbooksTitle": "操作手册来自团队已有的工作方式",
    "playbooksBody": "当 Avery 接入了你自己的 SOP、检查清单和过往决策后，会把它们提炼成可复用的操作手册——下次遇到类似情况，Avery 已经知道你的行事规则。",
    "playbooksSlotRoster": "入职与交接的 SOP 自动转成一步步可执行的操作手册。",
    "playbooksSlotIncident": "反复出现的情况沉淀为固定打法，Avery 每次都按同一套路走。",
    "playbooksSlotPack": "行业包（先从酒店业开始）会预置可直接套用的打法，你可以按需调整。",
    "playbooksSlotLabel": "这里会有什么",
    "playbooksComingSoon": "暂未接入——这里是 Avery 接下来会落地的方向预览。",
    "playbooksEmptyTag": "暂无操作手册",
    // rich-align-0722/08 · 满态方法库——以下 5 键手写 draft，待 Danny 审字（同 01-06 手写键口径）。
    "playbooksLibraryEyebrow": "操作手册",
    "playbooksLibraryTitle": "从你团队 SOP 整理出的操作手册",
    "playbooksLibrarySub": "Avery 读了你们的标准作业流程（SOP），把它们提炼成一张张方法卡——Avery 早已在跑的那些打法。",
    "playbooksLibraryAria": "操作手册——方法库",
    "playbooksCardTagsAria": "标签",
    "playbooksReopenOnboarding": "重看上手引导",
    "visionEyebrow": "完整版预告",
    "visionTitle": "你刚才试的是 demo。这背后才是产品。",
    "visionLede": "其它标签页里跑的一切，都基于你自己上传的文件。这是有意为之——这是最快的方式，让你感受到 Avery 是如何读懂一个团队的。真正的产品，比这再往前走一步。",
    "visionNowLabel": "你刚才用的",
    "visionNowTitle": "一份用你自己的文件驱动的 demo",
    "visionNowBody": "你丢进来一份花名册和一份计划，看着团队信息被整理出来，并向 Avery 提了一个真正的问题。这里没有为你写好的脚本——它读的是你给它的内容。这是一个公开的、可自助试用的版本，不是已部署的产品。",
    "visionRealLabel": "Avery 真正是什么",
    "visionRealTitle": "为一家公司量身打造的定制 agent",
    "visionRealBody": "在生产环境里，Avery 是为你的公司专门配置的——接入你自己的系统与文档，部署在你自己的安全环境内，而不是一个共享环境。它始终是一个聚焦的、领域专属的 agent，只认识你的团队，所以访问是有边界的、可审计的，而不是一个大模型到处伸手。",
    "visionProofLabel": "这份 demo 在证明什么",
    "visionProofTitle": "三件今天值得你判断的事",
    "visionProofUiux": "界面——一支团队、一场实时解读，动起来到底是什么手感。",
    "visionProofJudgment": "判断——Avery 对一个真实情境的解读，是不是你愿意信的那种。",
    "visionProofRedline": "这道边界——Avery 能不能给人打分，是公司自己握着的一道开关，默认关着，要开得有人显式去拧。关着时，涉及给人打分的内容在入口就被挡回去；开着时，它会带着证据一起递进来，作为决策支持——但绝不单独构成人事决定的依据。",
    "visionSummaryLabel": "摘要",
    "visionSummary1": "Avery 把团队的真实文件，读成管理者能落地的判断——谁在扛什么事、项目到哪一步、哪些事需要你过目。",
    "visionSummary2": "你今天在试的，是这条路的演示端：上传、阅读、决策。真正的产品，是接上你公司自己的数据、私有化部署的专属 agent。",
    "visionSummary3": "边界交给你来定：给员工打分这件事，是一个由公司掌控的开关；Avery 的任何一句话，都不会成为人事决策的唯一依据。",
    "visionMockEyebrow": "接入你的数据之后",
    "visionMockTitle": "这条边界打开之后的样子",
    "visionMockLede": "这些是预览，不是你现在可以点的功能。我们把它们摆出来，是希望你诚实地判断方向——每一项都已标注，不会有任何一项被误读为已经交付。",
    "visionTagPreview": "预览",
    "visionTagComing": "即将",
    "visionTagMock": "模拟",
    "visionMockFilesTitle": "agent 自己的文件空间",
    "visionMockFilesBody": "Avery 为每家公司保留一个独立的私密文件空间——存放你的文档、它的工作笔记，以及它产出的文件。这样一次解读可以在上一次的基础上继续，而不是每次都从零开始。",
    "visionMockSkillsTitle": "技能、工具与 SOP，皆为你而设",
    "visionMockSkillsBody": "你那些反复出现的工作——怎么入职、怎么做复盘、怎么处理卡住的项目——会变成一个有名字的技能，每次都以同样的方式跑。可预期是设计出来的，不是靠 prompt 即兴发挥。",
    "visionMockLoopTitle": "在你离开时也在跑的工作",
    "visionMockLoopBody": "把一批情境交给 Avery，它会在后台按自己的节奏逐个处理。你回来时看的是结果——不是一场需要盯着的实时会话。最稀缺的是你的注意力，所以产品把它留到最后用。",
    "visionMockGateTitle": "边界是闸门，不是愿望",
    "visionMockGateBody": "把一个团队读偏了，代价是补不回的信任。所以公司选定的「要不要给人打分」这个立场，不是提示词里一句聪明的请求就能绕开的话——而是在每条观察落库的入口，由一道确定性检查来强制执行。关着，涉及给人打分的内容直接被拒；开着，则连同证据一起放行。",
    "visionMockPersonName": "一位团队成员",
    "visionMockPersonRole": "读的是他做什么、扛什么——不是一个数字。",
    "visionComingSoon": "这四项目前都尚未上线。这个标签页是这条边界的预览，故意保持诚实。",
    "briefingEyebrow": "来自你上传的文件",
    "metricsLabel": "团队一览",
    "briefingHeadline": "你的团队：{people} 位成员，{projects} 个进行中的项目。",
    "briefingHeadlineFilesPartial": "读取了 {ingested}/{uploaded} 份文件：{people} 位成员，{projects} 个进行中的项目。",
    "briefingSubheadRisk": "以下内容全部来自你上传的文件，没有一处是编的。其中 {atRisk} 个项目值得注意。",
    "briefingSubheadRiskItems": "以下内容全部来自你上传的文件，没有一处是编的。其中 {atRisk} 处值得注意。",
    "briefingSubheadCalm": "以下内容全部来自你上传的文件，没有一处是编的。文件里没有读出风险信号。",
    "briefingMetricPeople": "位成员",
    "briefingMetricProjects": "个进行中的项目",
    "briefingMetricNeedLook": "个值得注意",
    "handoffsTitle": "今日提醒",
    "handoffsEmpty": "暂时没有需要你出面的事——文件读起来一切平稳。",
    "handoffsEmptyButLook": "眼下没有需要你出手的事——不过有 {count} 处值得注意，就在本页「资料对不上的地方」里。",
    "handoffOpen": "打开项目",
    "handoffToneLabel": "值得注意",
    "handoffAction": "{project}：今天先过一下",
    "handoffEvidenceFallback": "文件里，{project}的状态标记为「{status}」。",
    "handoffEvidenceTag": "来自你上传的文件",
    "handoffStatusAtRisk": "有风险",
    "handoffStatusBlocked": "受阻",
    "personReadOwns": "负责：{items}",
    "personReadListSeparator": "、",
    "personReadNone": "团队成员",
    "personCardOpenAria": "打开{name}——{read}",
    "streamNudgeRedline": "再核对一遍，只描述工作本身，不给任何人贴标签。",
    "streamNudgeChain": "先把回答落到证据上，再动手起草。",
    "streamAskDrafted": "一条快问已拟好，等你确认",
    "streamAdviceReady": "分析完成",
    // ⚠ 原值就两个字「好了」——这是「advise 跑完但没出结论卡」那一路的唯一收尾提示，
    //  两个字说不出**什么**好了、更说不出「其实没结论」。
    "streamAdviceDone": "这一轮跑完了，没有得出结论",
    "streamFailed": "连上 Avery 时出了点状况。",
    "streamErrorUnknown": "暂时没拿到失败详情。",
    "triageRemaining": "还有 {pending}/{total} 待处理",
    "triageDoneAria": "已完成 — {action}",
    "triageDiscardLabel": "今天先跳过",
    "triageTakeToRoomLabel": "去问 Avery",
    "triageAddFollowupLabel": "加到待办",
    "triageDraftMailLabel": "起草消息",
    "triageDrawerLabel": "今天已处理",
    "triageSetAsideLabel": "已搁置",
    "triageRestoreLabel": "恢复",
    "triageAllDone": "今天的提醒都处理完了。",
    // ⚠「会话」在这两句里指的是**公司数据**不是对话——经理会以为在恢复聊天记录，
    //  #78 落地真线程之后这个歧义更贵了。统一说「资料」。
    "restoringLabel": "正在载入你上次的资料…",
    "restoreFailed": "暂时连不上服务器，没能载入上次的资料。",
    "restoreRetry": "重试",
    "emptyEyebrow": "开始上手",
    "emptyHintRoster": "团队花名册或几份简历都可以——成员会以卡片形式出现。",
    "emptyHintProject": "项目计划或周报都可以——项目会排在他们旁边。",
    "emptyHintPrivacy": "给人打分这件事，是公司握着的开关——在打开之前，Avery 只记大家做了什么、在负责什么。",
    "peopleLane": "人员",
    "projectLane": "项目",
    "roomEmptyTitle": "把眼下的问题交给 Avery",
    "roomEmptyBody": "把团队里让你放心不下的事写下来——它会对照你上传的资料想清楚，再给你一份判断。",
    "roomNoMaterialTitle": "还没有可参考的资料",
    "roomNoMaterialBody": "Avery 还没读到你们团队的任何文件，没有事实可以支撑判断——它也不会瞎编。先上传一份花名册、一份项目计划，或者一份周报。",
    "roomNoMaterialCta": "去上传资料",
    "refAll": "全部",
    "refPeople": "人员",
    "refProjects": "项目",
    "refFiles": "文件",
    "refPlaybooks": "操作手册",
    "refEmpty": "先上传几份文件——成员和项目会出现在这里。",
    "refMenuAria": "引用候选",
    "composerFilterAria": "筛选引用候选",
    "composerRefsAria": "这次提问引用的对象",
    "composerRemoveRefAria": "移除 {label}",
    "refWeavePrefix": "涉及：",
    "refWeaveSeparator": "、",
    "searchPlaceholder": "搜索成员、项目…",
    "searchAria": "搜索成员与项目",
    "searchEmpty": "没有匹配的成员或项目。",
    "askAveryLabel": "问 Avery",
    "askAveryAria": "向 Avery 提问",
    "askAveryPlaceholder": "向 Avery 问一句关于团队的事…",
    "detailAria": "详情",
    "detailClose": "关闭",
    "detailPersonEyebrow": "团队成员",
    "detailProjectEyebrow": "项目",
    "detailTenure": "在职时长",
    "detailOwns": "手上的事",
    "detailCollab": "协作中的伙伴",
    "detailSummary": "概览",
    "detailProgress": "进度",
    "detailBlockers": "值得注意",
    "detailSignals": "文件里提到的",
    "detailSignalSource": "（来自《{source}》）",
    "detailGone": "这张卡片已不在你上传的文件里。",
    "detailStatus": "状态",
    "detailOwner": "负责人",
    "detailDue": "到期",
    "tabProjects": "项目",
    "projectsEyebrow": "项目",
    "projectsTitle": "你文件里的项目",
    // ⚠「文档未提及」逐字保留——G1（verify-locale-parity.mjs:62）与 G2（verify-status-truth.mjs:274）
    //  两道门都钉着它，且它本身就是 absent≠none 红线的字面。
    "projectsLede": "这一页的内容全部来自你上传的资料。文档里没写的状态、日期和数字，这里会明确标成「文档未提及」——不是 0，也不是空白。",
    "projectsCountOne": "从你的文件里读出 1 个项目",
    "projectsCountMany": "从你的文件里读出 {count} 个项目",
    "projectsCoverageTitle": "文件里没写的部分",
    "projectsCoverageProgress": "{count} 个没写进度",
    "projectsCoverageDue": "{count} 个没写到期",
    "projectsCoverageStatus": "{count} 个没写状态",
    "projectsCoverageNote": "这些地方 Avery 宁可留着「未提及」，也不替你的文件填一个 0。",
    "projectsSingleNote": "从你上传的文件里只读出了 1 个项目。如果文件里其实写了不止一个，多半是它们还没被拆成 Avery 能分辨的段落——每个项目单起一个小标题再上传，通常会好很多。",
    "projectsEmptyTitle": "还没有项目",
    "projectsEmptyBody": "去「资料库」上传一份项目计划、周报或进度汇总，里面写到的项目就会出现在这里。",
    "projectsEmptyCta": "去「资料库」上传",
    "projectsGroupNeedsYou": "需要你出手",
    "projectsGroupMoving": "在推进",
    "projectsGroupOther": "其它状态",
    "projectsGroupUnknown": "文件里没写状态",
    "projectsGroupDone": "已完成",
    "projectsStatusBlocked": "受阻",
    "projectsStatusAtRisk": "有风险",
    "projectsStatusOnTrack": "按计划推进",
    "projectsStatusDone": "已完成",
    "projectsStatusUnknown": "状态未提及",
    "projectsOwnerLabel": "负责人",
    "projectsDueLabel": "到期",
    "projectsProgressLabel": "进度",
    "projectsBlockersOne": "1 处卡点",
    "projectsBlockersMany": "{count} 处卡点",
    "projectsUnknownValue": "文档未提及",
    "projectsOpenAria": "打开 {title}",
    "projectsRiskLabel": "风险",
    "projectsRiskHigh": "高风险",
    "projectsRiskMedium": "中风险",
    "projectsRiskLow": "低风险",
    "projectsMilestonesLabel": "里程碑",
    "projectsMilestoneDone": "已完成",
    "projectsMilestoneActive": "进行中",
    "projectsMilestoneBlocked": "受阻",
    "projectsMilestoneUpcoming": "未开始",
    "projectsMilestoneOther": "其他",
    // rich-align-0722/05a · 项目手编 CRUD——以下 17 键手写 draft，待 Danny 审字（同 04 目录键口径）。
    "projectsAddCta": "添加项目",
    "projectsAddSubmit": "添加",
    "projectsAddFormAria": "添加项目表单",
    "projectsEditFormAria": "编辑项目表单",
    "projectsFieldTitle": "标题",
    "projectsStatusUnset": "未设置",
    "projectsProgressOptional": "选填 0-100",
    "projectsWriteFailed": "未能保存",
    "projectsManualBadge": "手动编辑",
    "projectsFormBadge": "来自周报填写",
    // ⚠ HAND-WRITTEN, NOT YET M3（T10）：这一格被一份**更新的**资料顶掉过，出处指向那一份。
    // 🔴 只印文档名不印行号（实体出处的行号是块级兜底，可能指向一个标题行）。
    "projectsDocBadge": "读自{source}",
    "projectsArchivedTitle": "已归档（{count}）",
    "projectsArchivedAria": "已归档的项目",
    "projectsArchivedRestore": "恢复",
    "projectsArchivedNote": "这个项目已归档。",
    // issue #93 · 「已并入」区 —— 补传之后粒度闸把资料里的检查点/阶段并进了对应的项目卡。
    // 🔴 与「已归档」故意不同词、也故意没有恢复键：归档是经理自己收的，这是系统判的，而重判
    //    每次补传都跑全档案 —— 手动放回来的卡下一次上传会被原样再折，那是个会自己撤销的按钮。
    //    这个区回答的是那个具体的问题：「我资料都传完了，那张卡怎么没了。」
    "projectsFoldedTitle": "已并入其他项目（{count}）",
    "projectsFoldedAria": "已并入其他项目的条目",
    "projectsFoldedLede": "这几条在你上传的资料里，是别的项目下面的检查点或阶段，已经并进对应的项目卡，不单独占一张。",
    "projectsFoldedNote": "原文都还在。删掉判定它的那份资料，它会自动回到上面的网格。",
    "projectsFoldedInto": "已并入「{title}」",
    "projectsFoldedIntoUnknown": "已并入另一张项目卡",
    "projectsFoldedEvidence": "依据：{source}",
    "detailEdit": "编辑",
    "detailSave": "保存",
    "detailCancel": "取消",
    "detailArchive": "归档",
    // rich-align-0722/06 · 人员手编 CRUD——以下 12 键手写 draft，待 Danny 审字（同上口径）。
    "peopleAddCta": "添加成员",
    "peopleAddSubmit": "添加",
    "peopleAddFormAria": "添加成员表单",
    "peopleEditFormAria": "编辑成员表单",
    "peopleFieldName": "姓名",
    "peopleFieldRole": "职位",
    "peopleFieldTeam": "组别",
    "peopleOwnsHint": "逗号分隔",
    "peopleDeactivate": "停用",
    "peopleArchivedTitle": "已停用（{count}）",
    "peopleArchivedAria": "已停用的成员",
    "peopleArchivedNote": "这名成员已停用。",
    "selfReportLoadLabel": "自述负载",
    "selfReportMoodLabel": "自述情绪",
    "selfReportMoodSteady": "如常",
    "selfReportMoodStretched": "偏紧",
    "selfReportMoodStrained": "吃紧",
    "selfReportMoodOther": "其他",
    "selfReportProvenance": "《{source}》记录的本人自述",
    "directoryGroupAllLabel": "全部",
    "directoryGroupAllAria": "显示全部成员",
    "directoryGroupFilterAria": "只看{group}",
    "directoryUngroupedLabel": "未分组",
    "directoryMoodRowLabel": "自述情绪",
    "directoryMoodFilterCaption": "按本人自述筛选",
    "directoryMoodAllLabel": "全部",
    "directoryMoodAllAria": "显示全部情绪",
    "directoryMoodFilterAria": "只看自述{mood}的成员",
    "directoryEmptyFiltered": "没有符合该筛选的成员。",
    "onboardEyebrow": "开始上手",
    "onboardCloseAria": "关闭 —— 下次会从上次停下的地方继续",
    "onboardSkip": "跳过设置",
    "onboardBack": "上一步",
    "onboardNext": "下一步",
    "onboardFinish": "进入",
    "onboardStepsAria": "设置步骤",
    "onboardStepOf": "第 {n} 步，共 {total} 步",
    "onboardBrowse": "先自己逛逛",
    "onboardDoorsTitle": "想从哪里开始？",
    "onboardDoorsBody": "两条路。示例团队最快看到全貌；用自己的文件起步，Avery 读的就是你们公司的现实。",
    "onboardDoorsBodySolo": "用自己的文件起步，Avery 读的就是你们公司的现实。",
    "onboardDoorDemoTitle": "用一份示例团队先看看",
    "onboardDoorDemoBody": "一份真实的示例团队（已脱敏）——花名册、项目和文档，Avery 已经读完。点一下就进，不用上传。",
    "onboardDoorDemoBusy": "正在准备示例团队…",
    "onboardDoorDemoErrorLead": "没法取到示例团队——",
    "onboardDoorUploadTitle": "用自己的文件开始",
    "onboardDoorUploadBody": "把花名册、计划、周报交给 Avery——它会读成一张能用的图。大概三步。",
    "onboardUploadTitle": "先从几份文件开始",
    // #91 · 与 upload.caption 同一条多选引导（一起读更快更准）。⚠ HAND-WRITTEN。
    "onboardUploadBody": "把你会交给一位新上任经理的第一份材料给 Avery——花名册、项目计划、一份周报。选文件时可以一次全选：几份一起读更快，结果也更准。它会把这些读成一张能用的图：人、项目、需要你过目的事。跳过也行，之后从「团队」里也能上传。",
    "onboardUploadChoose": "选择文件",
    "onboardUploadReading": "正在读取文件…",
    "onboardUploadHint": "正在逐页通读，通常需要两三分钟，期间可以先进行下一步。",
    "onboardUploadElapsed": "已用时 {seconds} 秒",
    "onboardUploadReady": "团队已就绪",
    "onboardUploadError": "没能读取这些文件 —— 再试一次，或者先跳过、稍后再上传。",
    "onboardUploadIdle": "还没上传文件 —— 这一步可以跳过。",
    // partner-docs-0728 · 闸门上传步的那条链接（新标签页打开，理由见 en.ts）。M3 生成，2026-07-28。
    "onboardUploadFormsLink": "不知道该发什么？拿一份标准表单",
    "onboardTeamTitle": "关于你的一点信息",
    "onboardTeamBody": "这几项只用来在界面上称呼你，只存在这台浏览器里。只有最后一栏例外：它会交给 Avery，让分析贴着你们公司的实际情况。",
    "onboardCompanyLabel": "公司",
    "onboardCompanyPlaceholder": "如：Harbor & Co.",
    "onboardDeptLabel": "团队或部门",
    "onboardDeptPlaceholder": "如：运营部",
    "onboardNameLabel": "Avery 该怎么称呼你？",
    "onboardNamePlaceholder": "如：Alex",
    "onboardTeamCountLabel": "团队人数",
    "onboardTeamCountPlaceholder": "如：20",
    "onboardRoleLabel": "你的职位",
    "onboardRolePlaceholder": "如：市场总监",
    "onboardCompanyNoteLabel": "现在想让 Avery 了解公司的哪些情况？",
    "onboardCompanyNotePlaceholder": "如：度假地产营销；十月进入旺季；今年的回款比去年慢一些……",
    "onboardCompanyNoteHint": "这段话只发给 Avery——会落到团队的笔记里，你随时能回看。",
    "onboardCompanyNoteHintLater": "这段话会和你的文件一起交给 Avery——等你的工作区建好就发出。",
    "onboardNoteText": "来自初始设置——你向 Avery 介绍的公司情况：{note}",
    "onboardNoteSource": "初始设置 · 关于公司",
    "homeDemoNote": "一份已脱敏的真实资料，Avery 已经读完。点一下就能用，是你自己的一份。",
    "onboardPlaybooksTitle": "挑几套适合你做事方式的打法",
    "onboardPlaybooksBody": "你挑的打法会决定「操作手册」标签页的样子 —— 它会显示每一套打法在接入你自己的 SOP 之后会长成什么样。目前还没接入，页面上也写明了。",
    "onboardDoneTitle": "准备好了",
    "onboardDoneGreeting": "{name}，很高兴见到你。",
    "onboardDoneGreetingNoName": "很高兴见到你。",
    "onboardDoneSummaryLead": "你挑的打法：",
    "onboardDoneNoPicks": "没有选打法——「操作手册」页会保持通用预览。",
    "playbookOnboardingTitle": "新人第一个月",
    "playbookOnboardingBody": "你的入职与交接流程，落成一步步可走的打法。",
    "playbookWeeklyTitle": "每周一回看",
    "playbookWeeklyBody": "每周用同样的方式，固定过一遍项目和卡点。",
    "playbookStuckTitle": "项目卡住时",
    "playbookStuckBody": "一段沉稳的步骤，帮你找到项目到底卡在哪里。",
    "playbookHandoffTitle": "交接与代班",
    "playbookHandoffBody": "有人不在时谁接什么 —— 提前说清楚，不必事到临头再商量。",
    "playbookToughTalkTitle": "在一次难谈话之前",
    "playbookToughTalkBody": "坐下谈之前，先把事实和一句温和的开场握在手里。",
    "playbookNinetyTitle": "经理上任的头九十天",
    "playbookNinetyBody": "读什么、见谁、一开始什么别碰。",
    "playbookRisksTitle": "早一点听到风险",
    "playbookRisksBody": "养成一个习惯：在小担心变大之前，先问问团队的工作情况。",
    "playbookShipTitle": "交付之后",
    "playbookShipBody": "趁记忆还热，简短回看 —— 哪些留、哪些改。",
    "playbooksChosenLabel": "设置时挑的",
    "playbooksChosenTag": "即将",
    "playbooksForCompany": "为 {company} 设置。",
    "roomChipsLabel": "试试这样问",
    "roomChipAttention": "这周团队里有谁可能需要我搭把手？",
    "roomChipRisk": "哪个项目最可能延期，为什么？",
    "roomChipHandoff": "目前有没有哪个交接正等着某个人？",
    "roomChipPlanning": "帮我列一下下周的重点。",
    "roomFlowTitle": "分析过程",
    // ⚠「原始流」是 raw stream 的直译，开发者词。三条一起改，`roomFlowFailed` 里那句
    //  「展开原始流可以看到…」也必须同步——否则文案自己指着一个已经不存在的按钮名。
    "roomFlowRawTitle": "原始日志",
    "roomFlowShowRaw": "查看原始日志",
    "roomFlowHideRaw": "收起日志",
    "roomToolLabel": "工具",
    "roomManifestLabel": "结果",
    "roomPhaseRead": "读取资料",
    // 「交叉验证」是统计/ML 的 cross-validation，这里含义完全不同，别借词。
    "roomPhaseCrosscheck": "核对信息",
    "roomPhaseMethod": "选定处理方式",
    "roomPhaseAct": "给出建议",
    // 与「已完成／进行中」同族的短词，且更短——帮窄屏。
    "roomPhasePending": "未开始",
    "roomFlowSteps": "{count} 步",
    "roomFlowSources": "读了 {count} 份资料",
    "roomFlowRecall": "从资料里找到 {count} 条相关内容",
    "roomFlowReady": "已给出结论",
    // 这是个可点按钮（RoomScreen.tsx:174-182），动词开头更像按钮。
    "roomFlowCites": "引用了 {count} 处原文",
    "roomFlowCitesLabel": "引用的原文",
    "roomFlowUnresolved": "没找到对应原文",
    "roomFlowFailed": "这次分析中断了。查看原始日志可以看到停在哪一步。",
    // ⚠ HAND-WRITTEN, act-first（#75 · 议事室 Claude 化 + #73 现场附件）：
    // 新部件的新键。停止生成一族（roomStop*/roomFlowInterrupted）+ 附件一族（roomAttach*）。
    // 🔴 所有 *Aria 值必须纯中文：verify-aria-zh 判「≥2 个连续拉丁词、或单个长度≥4 的拉丁词」
    //    即红，白名单只有 Avery|demo。所以「Enter / Shift」这类键名一个字都不许进 aria。
    // 与 roomFlowFailed 分开写而不是共用一句：断流是「它断了」，中断是「你按的」，
    // 把两件事说成同一句会让人以为自己按停时系统出了故障。
    "roomFlowInterrupted": "你按了停止，分析停在这里了。",
    "roomStopLabel": "停止",
    "roomStopAria": "停止本次生成",
    // ⚠ HAND-WRITTEN（#81 · composer 现代化）：发送键从文字钮「提问」换成箭头 icon 之后，
    //  它的可及名从「可见文字」变成了这条 aria-label。🔴 忘了传的话**一道门都不会红**——
    //  verify-aria-zh 只扫「已经存在的属性值」，扫不到「该有而没有」（recon-composer §4.2 暗区）。
    //  所以 room-claude-rework 里另加了一条「composer 每枚 icon-only 钮都有纯中文 aria」的判据。
    "roomSendAria": "发送这一问",
    "roomAttachAria": "上传文件一起问",
    "roomAttachRowAria": "这一问带上的文件",
    // 100 到 120 秒是实测区间，所以说「一两分钟」而不是「马上好」。
    "roomAttachBusy": "正在读，大概要一两分钟",
    "roomAttachFailed": "这份文件没读进来",
    // 移除只是「这一问不引用它」——文件已经进资料库了，删文件是另一回事（#77）。
    // 措辞照这个事实写，别让人以为按 × 就撤销了上传。
    "roomAttachRemoveAria": "这一问不引用 {label}",
    "roomAttachTooMany": "一次最多传 {max} 个文件",
    "roomAttachTooLarge": "{name} 超过 {max}，传不了",
    "roomAttachBatchTooLarge": "这一批加起来超过 {max}，传不了",
    "bellAria": "通知",
    "bellTitle": "收到的消息",
    "bellEmpty": "暂无消息。资料读完、或者 Avery 分析完一轮，都会通知你。",
    "bellMarkAll": "全部标为已读",
    "bellUnreadAria": "{count} 条未读",
    "notifIngest": "团队已就绪 —— 你带来的文件都读完了。",
    "notifRun": "分析完成 —— 结果可以看了。",
    "notifAsk": "你的快问，回复都收齐了。",
    // ⚠ 原文与「今日提醒」的 handoffToneLabel「值得注意」撞词，点进去却跳到差距块。
    //  ⚠ G10 禁的是 notifForm 不许含「值得注意」（verify-forms-proactive.mjs:178），本键不受它管，
    //  但把这个词从这里拿走顺带让那条判据的语义面更干净。
    "notifGap": "资料里有一处对不上。",
    // T9 · 表单这一路。🔴 与上面四条同一条红线：泛化文案，永不点名员工个人——结构上也没有
    // 携带人名的槽位（NotifItem 只有 kind）。「有人交了」而不是「周雅交了」是刻意的。
    "notifForm": "表单收集有新进展 —— 去「文件与表单」看一眼。",
    "footerText": "Avery 只辅助你的判断，不替你做决定。这里的每一条读数，都要经过你亲自复核才能算数；涉及岗位、薪酬、员工去留的重大人事决策，不能只拿它当依据。",
    "draftAria": "起草消息",
    "draftEyebrow": "由你来发",
    "draftTitle": "起草消息",
    "draftClose": "关闭",
    "draftRecipients": "发给",
    "draftRecipientHint": "这里是名字，不是邮箱地址——你的文件里只给到了名字。邮件出口打开时收件人是空的，地址请你自己填。",
    "draftNoRecipient": "文件里没写这条该发给谁——收件人请你自己填。",
    "draftSubject": "主题",
    "draftBody": "正文",
    "draftBodyHint": "这份草稿出自你文件里真实写着的内容。发之前先改成你自己的口气——最后是你在发这条消息。",
    "draftCopy": "复制",
    "draftCopied": "已复制",
    "draftCopiedStatus": "已复制——去你们平时说话的地方粘贴就行。",
    "draftCopyFailed": "没能写进剪贴板——请手动选中上面的正文复制。",
    "draftMailto": "改用邮件",
    "draftDoneAdd": "完成并加入待办",
    "draftDoneComplete": "完成并标记已办",
    // ⚠「队列」是开发词；那个 tab 的名字是「待办清单」（tabFollowups），照它说。
    "draftAddedStatus": "已加入待办清单。",
    "draftCompletedStatus": "已在待办清单里标记为完成。",
    "draftGoFollowups": "去待办清单",
    // ⚠ 手写中文，非 M3 生成（feat-057）：聚合首屏一段。源键在 en.ts。
    // AGENTS.md 已授权 act-first 直接定稿，不标"待审"。
    // 🔴 这一屏上的每个数字都由 homeDerive.ts 从真 payload 数出来——文案里绝不写死任何统计数
    //（参考库那句"扫描了 186 条信号"是硬编码的，我们一条都不搬）。
    // 🔴 不许在这里承诺「重新传一次就好了」。定级由后端的规则层算（feat-056），
    // 后端没上这个能力时，客户重传多少次都不会有结果——那句承诺会把人按在一个
    // 永远走不通的动作上循环。两种成因的补救动作相反，而这份数据分不出是哪一种，
    // 所以两种都摊开讲，不替客户挑一个。
    "tabHome": "今天",
    "homeEyebrow": "今天",
    "homeTitle": "今天有几件事需要你确认",
    "homeLede": "都是从你上传的文件里读出来的。每一块都能点进去看细节。",
    "homeSkeletonTitle": "你每天从这里开始",
    // ⚠ #79 见仁见智⑧拍板：**只缩字数、不改结构**（每条仍然只讲「这一块将来会显示什么」）。
    //  理由是 1366×768 上空态卡垂直居中、让位余量是视口高度的函数——原文每条 33-41 字，
    //  五条叠起来会把眉题顶进顶栏。三句带红线语义的（不会编造 / 只数次数不作评价 /
    //  数字都是实际读到的）**一个字都不许删掉那半句**，所以它们的缩幅小于一半。
    //  🔴 verify-home-skeleton.mjs:45-46 判 `.lite-home-skeleton-blocks` 整块**零数字**
    //  （`/[0-9０-９]/`）——下面四条里一个阿拉伯数字都不能有。
    "homeSkeletonLede": "下面每一块都只来自你上传的资料，不会编造。",
    "homeSkeletonDecisions": "今天值得你定的事会排在这里，每条都带着原文。",
    "homeSkeletonGaps": "项目自报的状态和卡点对不上时，会出现在这里。",
    "homeSkeletonAttention": "反复被提到的人会出现在这里，只数次数，不作评价。",
    "homeSkeletonOverview": "人、项目、文件、笔记、待办——数字都是实际读到的。",
    "homeGuestNote": "不用注册账号也能用——所有功能对访客都开放。先登录再上传，传的东西会记在你名下，换台设备登录也能找回。",
    "homeTodayTitle": "今日待办",
    "homeTodayEmpty": "今天还没有待办。从决策、对话、「资料对不上的地方」加进来的事都会出现在这里。",
    "homeTodayDoneAria": "把「{title}」标记为已完成",
    "homeTodayMore": "列表里还有 {count} 项",
    "homeDecisionAddFollowup": "加到待办",
    "homeDecisionFollowupTitle": "决策：{title}",
    "homeDecisionsTitle": "今天要决策的",
    "homeDecisionsCount": "共 {total} 条",
    // ⚠「定级」是后端词（decision_grading.py），界面上没有任何地方叫「定级」；
    //  「后端」更是**开发词直接印给了客户**（原文出现两次）。三条一起换成经理的话。
    "homeDecisionsOrderNote": "按重要程度排序，最要紧的在最前。",
    "homeDecisionsAbsentTitle": "这份资料还没有分级结果",
    "homeDecisionsAbsentBody": "两种可能，这份资料本身分不出是哪一种。一种是它在分级功能上线之前就读进来了，重新上传一次就会有；另一种是当前服务还不支持分级，那么重传多少次都不会有，只能等我们跟上。",
    "homeDecisionsEmptyTitle": "今天没有要你定夺的事",
    "homeDecisionsEmptyBody": "等文件里出现卡点、过期的日子或风险信号，它会带着命中的规则出现在这里。",
    "homeDecisionOwner": "负责人",
    "homeDecisionReasonRule": "按规则判定",
    "homeDecisionReasonAvery": "Avery 的判断",
    // ⚠ HAND-WRITTEN, act-first（票 #38 · ADR-0033，2026-08-03）：以下 decisionGrades /
    //  homeDecisionReasonByRule / homeDecisionReasonNoRule / homeDecisionRuleJoin / decisionRules
    //  这一整块，是从后端搬过来的——在此之前这些句子由 decision_grading.py / decision_rules.py
    //  写死成中文随载荷发下来，英文用户因此拿到中英夹杂的判读面板。ADR-0033 后后端只发机器键
    //  （high_risk / R-BLOCKER-STACK），句子在这里出，zh/en 各一份。
    //  🔴 没跑 i18n-zh.mjs / i18n-zh-delta.mjs：① 对象体里有 8 行 feat-057 红线注释，delta 的
    //  JSON.stringify 写法会连它们一起抹掉；② 2026-08-03 口径已改成「中英文都由当前 session
    //  自己写大白话」（AGENTS.md DoD 第 3 条），不再绕道 M3。源键在 en.ts（唯一源）。
    //  🔴 措辞红线（ADR-0018，与后端原文一字不让）：只许说「读到 / 没读到什么」，绝不许替客户
    //  断言「你的文档里没写 X」——他手上就有原件，一翻就露馅。
    "decisionGrades": {
      "high_risk": "高风险",
      "needs_confirmation": "需确认",
      "can_proceed": "可推进"
    },
    "homeDecisionReasonByRule": "按规则判为{grade}：{rules}。",
    "homeDecisionReasonNoRule": "无命中规则",
    "homeDecisionRuleJoin": "；",
    // {n}/{days}/{pct} 由命中的 `params` 填 —— 阈值仍归后端配置（decision_rules.py），
    // 这里只出句子。🔴 别把那几个数字写死进句子，那等于在下一层重开一个会静默漂的事实源。
    "decisionRules": {
      "R-SIGNAL-ATTRITION": { "title": "关联信号提到人员流失 / 离职", "basis": "关联信号 + 阻塞" },
      "R-SIGNAL-COMPLAINT": { "title": "关联信号提到客户投诉 / 退订", "basis": "关联信号 + 阻塞" },
      "R-SIGNAL-CONFLICT": { "title": "关联信号提到协作冲突", "basis": "关联信号 + 阻塞" },
      "R-SIGNAL-INCIDENT": { "title": "关联信号提到法务 / 安全 / 停工", "basis": "关联信号 + 阻塞" },
      "R-STATUS-BLOCKED": { "title": "项目自报状态为「已阻塞」", "basis": "状态" },
      "R-BLOCKER-STACK": { "title": "同时挂着 {n} 条及以上未解阻塞", "basis": "阻塞" },
      "R-OVERDUE": { "title": "到期日已过", "basis": "到期日" },
      "R-DUE-VS-PROGRESS": { "title": "{days} 天内到期、但自报进度不足 {pct}%", "basis": "到期日 + 进度" },
      "R-STATUS-AT-RISK": { "title": "项目自报状态为「有风险」", "basis": "状态" },
      "R-BLOCKER-ONE": { "title": "挂着 1 条未解阻塞", "basis": "阻塞" },
      "R-DUE-SOON": { "title": "{days} 天内到期", "basis": "到期日" },
      "R-PROGRESS-LOW": { "title": "自报进度不足 {pct}% 且未完成", "basis": "进度" },
      "R-SIGNAL-WATCH": { "title": "关联信号提到延期 / 返工 / 缺人等待办", "basis": "关联信号 + 阻塞" },
      "R-SELF-REPORT-MISMATCH": { "title": "自报「正常」但挂着未解阻塞（自述与信号不一致）", "basis": "状态 + 阻塞" },
      "R-STALE-EVIDENCE": { "title": "手上最新的一份资料也是 {days} 天以前上传的，之后没再读到新的", "basis": "资料上传时间" },
      "R-CROSS-DOC-CONFLICT": { "title": "同一件事在不同资料里读到了对不上的读数——需要确认以哪份为准", "basis": "跨资料同一字段的读数" },
      "R-FRESH-CONTRADICTS-STALE": { "title": "同一件事上，更新上传的那份资料读到了更糟的读数——旧读数可能已经过时", "basis": "跨资料同一字段的读数 + 资料上传时间" },
      "R-NO-EVIDENCE": { "title": "没读到状态、阻塞、进度、到期日中的任何一项——信息不足，不能当作没风险", "basis": "（这四个字段都没读到）" },
      "R-UNCLASSIFIED": { "title": "读到的字段没有落在任何一条现有规则的判据里，无法直接归类，需要人工确认", "basis": "（未命中任何规则）" },
      "R-FORM-MISSING": { "title": "本期还差 {n} 人没交，最早的一条链接 {hours} 小时内到期", "basis": "本期表单链接的状态 + 到期时间" },
      "R-DONE": { "title": "项目自报已完成，且无风险信号", "basis": "状态" },
      "R-CLEAR": { "title": "项目自报正常，无未解阻塞、无风险信号", "basis": "状态 + 阻塞" }
    },
    "homeDecisionEscalated": "Avery 调高了这条的等级",
    // B2b（#56）· 冲突卡的关闭出口。🔴 措辞红线（ADR-0018）：这不是错误提示，是请经理确认
    // ——两份都是他自己的资料，绝不说「你写错了」，也不替他断定哪份是对的。
    // 收起只影响他自己的看板（前端分桶），等级与资料原文一字不动。
    "homeConflictDismiss": "可能只是叫法不同",
    "homeConflictDismissedNote": "已按「可能只是叫法不同」收起。读数还在资料里，随时可以恢复。",
    "homeConflictRestore": "恢复",
    "homeDecisionRulesToggle": "判断依据",
    "homeDecisionRuleBasis": "看的字段",
    "homeDecisionEvidenceLabel": "文件原文",
    "homeDecisionUnknownLabel": "文档未提及",
    "homeDecisionUnparsed": "{field}写的是「{raw}」，无法确定具体值。",
    "homeDecisionOpenProject": "打开项目",
    "homeDecisionAskRoom": "去问 Avery",
    "homeFieldStatus": "状态",
    "homeFieldProgress": "进度",
    "homeFieldDueDate": "到期日",
    "homeFieldBlockers": "阻塞",
    "listJoin": "、",
    "labelSep": "：",
    "homeGapsTitle": "资料对不上的地方",
    "homeGapsCount": "{count} 处待确认",
    "homeGapsEmpty": "现在没有自相矛盾的地方。",
    "homeGapsFilterEmpty": "这个状态下暂时没有。",
    "homeGapFilterActive": "活跃",
    // #63：homeGapsLink（跳去已退休 tab 的链接）换成原地展开/收起一对。
    "homeGapsExpand": "全部展开",
    "homeGapsCollapse": "收起",
    "homeAttentionTitle": "资料里反复提到的人",
    "homeAttentionCaption": "数的是文件里提到的次数，不是对任何人的评价。",
    "homeAttentionWhySignals": "出现在 {count} 条信号里",
    "homeAttentionWhyBlockers": "名下项目挂着 {count} 条卡点",
    "homeAttentionEmpty": "目前资料里没有特别集中提到某个人。",
    "homeAttentionLink": "团队",
    "homeOverviewTitle": "资料概览",
    "homeOverviewPeople": "人",
    "homeOverviewProjects": "个项目",
    "homeOverviewFiles": "份文件已读",
    "homeOverviewNotes": "条笔记",
    "homeOverviewFollowups": "条待跟进",
    // ⚠「判读」是气象/雷达/影像的专业词，日常中文里没人用它指「分析结论」。本票统一改「结论」，
    //  同族五个键（adviceReadTitle / adviceCardAria / adviceSummaryAria /
    //  adviceConfidenceWouldChange / streamAdviceReady）一起走，别只改一半。
    "adviceCardAria": "Avery 的分析",
    "adviceEyebrow": "Avery 的分析",
    "roomAnswerLabel": "Avery 的回答",
    "roomTurnQuestionLabel": "你的提问",
    "roomFollowupsLabel": "继续追问",
    // ⚠ #78 已把它旁边的计数单位从「条」改成「场」（roomHistoryCount「{n} 场」），
    //  两者渲染成「历史对话 · 3 场」，读得顺。
    "roomHistoryTitle": "历史对话",
    "roomHistoryCount": "{n} 场",
    "roomHistoryTurns": "{n} 轮问答",
    // ⚠ #83 删掉了 `roomHistoryEmptyThread`（「单独问过一次」）。它是单轮场那一支的 meta 文字，
    //  0810 真数据实测 9 场里 8 场逐字相同——满行的墨、零信息。轮数改成只在 >1 时才占墨，
    //  这个键从此没有任何消费者，两份字典同拍删掉（留着就是 i18n-orphans 的一个孤儿）。
    "roomHistoryOpenAria": "打开这场对话，接着往下问",
    "roomHistoryCurrent": "就是眼下这场",
    "roomHistoryBusy": "这一轮还在答，答完才能切",
    // ── issue #80 · 常显侧栏 + 新对话 ──────────────────────────────────────────────
    // ⚠ 这一族全是**手工 Edit** 加的（`scripts/i18n-zh-lite2-delta.mjs` 会整个重写本文件，
    //  memory 碑；只读的 i18n-orphans 才可以跑）。
    // 侧栏空态：拉到了确实没有历史（adviseThreads === []）才说这句。null（还没拉/stub 通道）
    // 时列表区留白——「还没问过」和「还不知道有没有问过」是两件事，不许合并成一句。
    "roomHistoryEmpty": "还没有历史对话",
    // #83 · ≤860 抽屉遮罩的可及名。它是一枚铺满正文的按钮，唯一的动作就是把抽屉收回去，
    // 所以名字直接说这件事（纯中文，过 verify-aria-zh 的拉丁门）。
    "roomHistoryScrimAria": "收起历史对话",
    // 按日期分组的三个组标。分组键取**场内最后一轮**的 created_at（与列表排序键同源，
    // 不打架）；比较的是浏览器本地时区的日历日。
    "roomHistoryToday": "今天",
    "roomHistoryYesterday": "昨天",
    "roomHistoryEarlier": "更早",
    // 新对话钮。语义＝把屏上这场散掉、下一问开新的一场（下一问不带 thread_id，服务端自铸）。
    "roomNewLabel": "新对话",
    // 生成中禁点的原因（title 属性，不是 aria——它是解释不是名字）。同 roomHistoryBusy 的
    // 措辞纪律：说清楚为什么点不动，不留静默。
    "roomNewBusy": "这一轮还在答，答完才能开新的",
    "roomTurnFromHistory": "这轮是从历史载入的，当时的分析过程没有留存",
    "adviceReadTitle": "结论",
    "adviceSignOff": "最终由你决定",
    "adviceSummaryAria": "结论摘要",
    // ⚠ 下面这五条 section label 原本全是「认识论前缀 + 破折号 + 解释」（事实——／推断——／
    //  建议——／置信度——），那是设计稿的概念结构，每张卡要读五遍。改成直接说这一段是什么。
    //  它们同时是可见 label 和 aria-label（LiteAdviceCard.tsx:56-57/67-68/89-90/100-102/133-134），
    //  新值仍是纯中文，过 verify-aria-zh 的拉丁门。
    //  ⚠ lite 段有同名 v01 副本（zh.ts:481-503），随冻结壳纪律**一个都不动**。
    "adviceSignalsLabel": "读到的信号",
    "adviceHypothesesLabel": "可能的原因（推测，不是结论）",
    "adviceMostLikely": "最可能的情况",
    "adviceAlsoPossible": "也存在这种可能",
    "adviceBackingLabel": "依据",
    "adviceEvidenceLabel": "依据的原文",
    "adviceConfidenceLabel": "可信度",
    "adviceConfidenceWouldChange": "什么情况下结论会变",
    "adviceMoveLabel": "下一步",
    "adviceActionsLabel": "建议的下一步",
    // ⚠ `1:1` 与 `HR` 是外企黑话，国内经理未必懂。zh-purity 门的收尾纪律写得很直白：
    //  「HR→人事 是**改文案**解决的，没有塞进白名单——放宽纯度门去迁就一句能改好的中文，
    //  是把门本身花掉。」这三条正是那条纪律点名的例子，本票兑现它。
    "adviceScriptLabel": "如果你要找他单独谈",
    "adviceWatchLabel": "怎么判断有没有效果",
    "adviceHrAria": "人事 / 谁来把关",
    "adviceHrLabel": "什么时候找人事",
    "adviceEscalationNotYet": "暂时不用",
    "adviceConfirmsLabel": "谁来把关",
    "adviceConfidenceLow": "较低",
    "adviceConfidenceMedium": "中等",
    "adviceConfidenceHigh": "较高",
    // 「人力伙伴」是 HRBP 的半译，中文里不成词（原注释自认是为了对齐徽章长度硬裁的）。
    //  「人事」与同排的「法务／员工关怀／薪酬／高管层」同为 2-4 字，徽章宽度只变短。
    "adviceEscalationHRBP": "人事",
    "adviceEscalationLegal": "法务",
    "adviceEscalationWellbeing": "员工关怀",
    "adviceEscalationCompensation": "薪酬",
    "adviceEscalationExecutive": "高管层",
    "topbarAria": "Avery 控制栏",
    "screenNavAria": "屏幕导航",
    "roomBoardAria": "对话 —— 回答区",
    "roomAskAria": "向 Avery 提问",
    // ⚠ #79 · **新键**：v02 版的 `nexus.askPlaceholder`。共享那条写的是「向你的团队提问…」，
    //  那是 v01 的框架（它的屏叫「议事室」、隐喻是一屋子人）；v02 的对象是 Avery 本身。
    //  在这儿分叉而不是改共享键，是照 teamEmptyLead 从 team.emptyBody 分出来的先例
    //  （理由写在 zh.ts:703-704）——冻结壳一个字节不动。
    "roomAskPlaceholder": "向 Avery 提问…",
    "roomLiveQuestionAria": "当前提问",
    // ⚠ 原值「还在梳理中 —— …」挂在**空态** section 上，而空态什么都没在跑（同族的组件层
    //  病灶 #75 已经修掉：RoomScreen:845 那颗 eyebrow 是删的不是改的）。这里只留名字。
    "roomEmptyAria": "向 Avery 提问",
    "notesEmptyAria": "Avery 的笔记 —— 暂无内容",
    "playbooksEmptyAria": "操作手册 —— 即将上线",
    "teamLiveAria": "团队 —— 实时",
    "followupsViewAria": "跟进事项视图",
    "gapEmptyAria": "资料对不上的地方 —— 暂无待看",
    "projectsEmptyAria": "项目 —— 暂无内容",
    "complianceFooterAria": "如何使用 Avery 给你的建议"
  },
  "ask": {
    "eyebrow": "快问",
    "draftTitle": "直接问问本人",
    "draftLede": "资料里缺的那一块，在他们自己怎么看这件事。看一下这些问题，然后把各自的链接发给本人。",
    "redlineNote": "问题针对的是工作本身。能不能给人打分，是你们公司握着的开关——每条问题在每次保存时，仍会过一遍服务端的这道检查。",
    "redlineNoteOffline": "问题针对的是工作本身。这条服务端校验会在你保存时执行；本次离线预览不会写入任何内容，所以这里不跑。",
    "kindScale": "1–5",
    "kindYesNo": "是 / 否",
    "questionAria": "问题正文",
    "removeQuestion": "移除",
    "addScale": "加一道 1–5 分题",
    "addYesNo": "加一道是 / 否题",
    "maxQuestionsHint": "最多三道题——十秒内答完。",
    "commentPromptLabel": "他们可以再补一句自己的话：",
    "recipientsLabel": "问谁",
    "recipientsHint": "从你团队名单里选人——每人一条独立链接。",
    "confirm": "确认，生成链接",
    "confirmBusy": "正在生成链接…",
    "sharedTitle": "链接已生成——由你转发",
    "sharedLede": "你亲手把链接发给对应的人，在你们平时聊的地方都行——你没发，谁也收不到。",
    "copy": "复制链接",
    "copied": "已复制",
    "repliesChip": "{answered}/{total} 已回复",
    "closedChip": "回复收齐了",
    "refresh": "查看新回复",
    "refreshing": "正在刷新…",
    "receiptsTitle": "大家的回答",
    "selfReported": "本人自述",
    "selfReportedHint": "他们自己对这件事的描述——不是给他们的打分。",
    "receiptYes": "是",
    "receiptNo": "否",
    "receiptScaleSuffix": "/ 5",
    "summaryTitle": "汇总",
    "answeredAt": "回复于",
    "errorGeneric": "连不上快问服务——再试一次。",
    "offlinePreview": "离线预览——这些链接只是示意，点不开。",
    "expiryHint": "链接七天内有效，过期自动失效。",
    "revoke": "撤回这次快问",
    "revokedTitle": "已撤回",
    "revokedChip": "已撤回",
    "revokedNote": "你撤回了这次快问——链接打开后只看到撤回提示，不再显示问题，也不再接收回复。",
    "expiredTitle": "已过期",
    "expiredChip": "已过期",
    "expiredNote": "这次快问已过七天有效期，链接不再接收作答。如果还想听听他们的看法，重新发起一次。"
  }
};
